### ISSUE TITLE
API for /write example incorrect

### ISSUE THREAD

**Issue by gmucha** [spotify/heroic#10]
API documentation differs from implementation - actual data should be more deeply nested (`data` has `type` and actual `data` containing points).

```
{
    "series": {
        "key": "foo",
        "tags": {
            "site": "lon",
            "host": "www.example.com"
        }},

    "data" : {
        "type" : "points",
        "data": [
        [
            1300000000000,
            42
        ],
        [
            1300001000000,
            84
        ]
    ]
    }
}```

**Comment by udoprog** [comment]
Thanks for the report!
The issue should now have been solved. Please have a look.

**Comment by gmucha** [comment]
Looks OK. Trying to evaluate Heroic right now, as it actually touches a lot of the issues I'm seeing with KairosDb.

**Comment by udoprog** [comment]
Interesting, addressing some of those were part of the motivation behind creating Heroic.
Please join us on `#heroic at Freenode` if you want to discuss your project in more details.
