### ISSUE TITLE
"Sending GOAWAY failed"

### ISSUE THREAD

**Issue by valentinul** [spotify/heroic#111]
Hello everyone,

I'm new to heroic and not sure how to approach this error. 
I've configured the heroic API, using debian package built from git repo.
After the service starts I'm getting the following message every minute. 

`10:11:15.922 [heroic-scheduler#2] INFO  com.spotify.heroic.cluster.CoreClusterManager - [new] grpc://131.x.x.x:8100
10:11:15.929 [nioEventLoopGroup-2-6] INFO  com.spotify.heroic.cluster.CoreClusterManager - [refresh] no nodes discovered, including local node
10:11:15.929 [nioEventLoopGroup-2-6] INFO  com.spotify.heroic.cluster.CoreClusterManager - [update] [{}] shards: 1 result(s), 1 failure(s)
10:11:15.930 [nioEventLoopGroup-2-5] WARN  io.netty.handler.codec.http2.Http2ConnectionHandler - [id: 0x7ffeead0] Sending GOAWAY failed: lastStreamId '0', errorCode '2', debugData 'Connection refused: /131.x.x.x:8100'. Forcing shutdown of the connection.
java.nio.channels.ClosedChannelException
`

Any ideas why ?

**Comment by udoprog** [comment]
Hey, is the node at `131.x.x.x` configured to listen on port 8100 on gRPC?

This should be apparent in the configuration.

**Comment by valentinul** [comment]
Hi John,

Yes, this is my config
`# heroic.yaml
port: 8080

cluster:
  protocols:
    - type: grpc
  discovery:
    type: static
    nodes:
      - "grpc://131.x:8100"

consumers:
  - type: kafka
    schema: com.spotify.heroic.consumer.schemas.Spotify100
    topics:
      - "metrics"
    config:
      group.id: heroic-consumer
      zookeeper.connect: kafkabaer1.x,kafkabaer2.x,cassandra-node1.x
      auto.offset.reset: largest
      auto.commit.enable: true

metrics:
  backends:
    - type: datastax
      seeds:
        - cassandra-node1.x
        - cassandra-node2.x
        - cassandra-node3.x
        - cassandra-node4.x
        - cassandra-node5.x

metadata:
  backends:
    - type: elasticsearch
      connection:
        seeds:
          - "heroic-e.x"

suggest:
  backends:
    - type: elasticsearch
      connection:
        seeds:
          - "heroic-e.x"
shellServer:
  host: "131.x.x.x"
  port: 9190
`

**Comment by udoprog** [comment]
If you are only using one node, there is no need to have a `cluster` configuration.

But I believe the problem you are seeing is caused by the node in the `discovery` configuration using a different port than the one which is used by `grpc` by default: `grpc://131.x:8100` instead of omitting the port, like `grpc://131.x`.

**Comment by clwells** [comment]
Have been having a time getting Heroic going and one note here.  It seems like if you don't define which host/port GRPC should run on it won't start at all and you'll get an error like the OP did.  I "fixed" this by doing:

```
cluster:
  protocols:
    - type: grpc
      host: 131.x
      port: 8100
  discovery:
    type: static
    nodes:
      - "grpc://131.x:8100"
```

Hope it helps someone :)

**Comment by udoprog** [comment]
Yes, you are correct. We came to a similar conclusion in #139

Thanks for sticking with it!
