### ISSUE TITLE
Multiple separate/non-chained aggregations in one query?

### ISSUE THREAD

**Issue by hampusohlsson** [spotify/heroic#113]
Hey guys,

We're trying out Heroic in addition to a few other databases. Both KairosDB and OpenTSDB have the functionality to make multiple aggregations in the same query, and return them as separate result sets. 

More specific, is it possible to fetch the min/avg/max for a given metric, without sending 3 separate queries?

Any input appreciated. Thanks!

**Comment by hampusohlsson** [comment]
Thanks, just tried it out - works great!

For the multiple aggregations enhancement, the easiest(?) solution might be to add support for multiple queries instead. So instead of sending one JSON query object, I can pass an array of query objects. In that case the response would just be an array with the different result sets.

**Comment by udoprog** [comment]
I've added documentation about our batch endpoint: http://spotify.github.io/heroic/#!/docs/api/post-query-batch

Do keep in mind that batches are much more inefficient than spreads for your use-case, since the data will still have to be fetched multiple times from the metric backend.
