### ISSUE TITLE
Diff aggregations (deltas)

### ISSUE THREAD

**Issue by mykolasmith** [spotify/heroic#116]
Hi,

Are there any plans for a rate of change aggregator (deltas)? KairosDB has a "diff" aggregator that performs no sampling. We usually use it as the first aggregator in a chain to feed into downsampling aggregators (min, max, avg, etc.)

It seems like Heroic uses a concurrent bucketing pattern for `SamplingAggregation`, so it seems like a `FilterAggregation` would be more appropriate, since you would need to keep track of the state of the last point. Something like the `FilterKAreaStrategy` might work, which implements  `MetricCollection`, perhaps containing the two points at a time... e.g.:

```
private double computeDiff(MetricCollection metricCollection) {
    final List<Point> metrics = metricCollection.getDataAs(Point.class);
    return metrics.get(1).getValue() - metrics.get(0).getValue()
}
```

Am I on the right track?

**Comment by udoprog** [comment]
Hey,

You are on the right track conceptually, but `FilteringAggregation` is not a great base for what you are trying to accomplish. I'd suggest investigating implementing a completely custom aggregation which wraps around `Empty`/`EmptyInstance`, and performs the delta's in the `result` method.

I realize this is what filtering aggregations do, but they are a bit more opinionated right now. What you do could be generalized into another aggregation archetype, maybe one that filtering should inherit from.

Good luck, and don't hesitate to follow up if you have more questions.

**Comment by mykolasmith** [comment]
@udoprog Thanks, I'll keep you posted w/ progress & questions.

**Comment by mykolasmith** [comment]
@udoprog I've created `Delta / DeltaInstance` classes that extend `Empty / EmptyInstance`. It seems that `CollectorSession` in `EmptyInstance` is a private static final class. I'm not sure how to override the `result` function of a private class from within an extending class. Apologies, I am not a Java developer =( Would you be so kind as to set up the next few lines?

```public class DeltaInstance extends EmptyInstance {
    @JsonCreator
    public DeltaInstance() {
        super();
    }
}```

**Comment by udoprog** [comment]
There´s no need to extend EmptyInstance, you can keep it as a field of `DeltaInstance`.

```java
public class DeltaInstance {
    private final EmptyInstance inner = Empty.INSTANCE;

    /* implement methods and delegate calls to inner */
}
```

This is basically how it's used in `FilteringAggregation` here:
https://github.com/spotify/heroic/blob/master/aggregation/simple/src/main/java/com/spotify/heroic/aggregation/simple/FilterAggregation.java#L82

**Comment by mykolasmith** [comment]
I've got a working Delta aggregation and will open a pull request later today for further discussion.
