### ISSUE TITLE
How to select metrics?

### ISSUE THREAD

**Issue by valentinul** [spotify/heroic#117]
Hi,
I'm sure this is a noob question but how do I select metrics from heroic? 
I'm interested in doing this using grafana and also the heroicsh. 

Any input is appreciated.

**Comment by udoprog** [comment]
Try `average by *` if you have few metrics, or you can add more filtering by adding `average by * where what = foo and role = bar` for example.

The Grafana plugin only supports the DSL which is still being worked on, but it is relatively functional. Read more here:
http://spotify.github.io/heroic/#!/docs/query_language

**Comment by valentinul** [comment]
Hi,

Thanks for the select example, I didn't knew that I have to use actual queries in the grafana input. 
Everything works as expected now.
