### ISSUE TITLE
How to push metrics?

### ISSUE THREAD

**Issue by valentinul** [spotify/heroic#118]
Hi,

I'm making a json structure in logstash and pushing it into a kafka topic (works as expected) but it seems that heroic is not consuming the metrics for some reason.

My structure is the following

```
{
     "time" => "1477401246000",
     "host" => "host1.cc",
     "tags" => {
        "loginResult" => "ok",
          "loginType" => "sshd",
          "loginUser" => "xuser"
    },
      "key" => "c2uo0wqqn",
    "value" => "1.0"
}
```

If I connect to the shell server and run keys I only see the keys generated..

```
{"series":{"key":"key-11","tags":{"host":"11.example.com","role":"web","what":"disk-used"}},"base":1475321265489,"type":"points","token":6743956916690856207}
{"series":{"key":"key-81","tags":{"host":"81.example.com","role":"ingestor","what":"teleported-goats"}},"base":1475321265489,"type":"points","token":7120557367222539016}
{"series":{"key":"key-51","tags":{"host":"51.example.com","role":"ingestor","what":"disk-used"}},"base":1475321265489,"type":"points","token":7178361716493023162}
```

Any ideas what am I doing wrong? 

Thank you!

**Comment by udoprog** [comment]
Hey,

How have you configured Heroic, and how are you running it?

If you are getting generated metrics I suspect you are running an example configuration not intended for persistent use.

**Comment by valentinul** [comment]
Hi,
Sorry for the late reply! I managed to consume the metrics I was pushing to kafka.
The issues was with the schema/structure of the data
