### ISSUE TITLE
RFC: Flatten DSL

### ISSUE THREAD

**Issue by udoprog** [spotify/heroic#12]
This RFC suggests to introduce the two following syntactic sugars in aggregation DSLs, the **by** and the **| (pipe)** keywords.

**by** expressions take the form `<aggregation> by <tags>`, and are equivalent to the current `group(<tags>, <aggregation>)` syntax.

**| (pipe)** expressions take the form `<aggregation> | <aggregation> | ..`, and are equivalent to the current `chain(<aggregation>, <aggregation>, ..)`.

It is also possible to group expressions using parenthesis to override priority, like the following:
```
(average() by host | sum()) by role
```
Which would read as something like: *calculate the sum of all averages by host for each role*

The rationale behind the proposal is to *flatten* the need for overly nested expressions, and to allow for aggregations to read from left to right more naturally what their intent is.

Take the following example:
```
chain(group([host], average()), group([host], sum()))
```

This could be written as the following:
```
average() by host | sum() by site
```

This would read as: *average by host, then sum by site*.

## alternative to pipe

Pipe has very strong connotations, especially when considering shell pipes. It might be inadvisable to use such a well-established keyword. I'm open for proposals of alternative operators or syntax.

An alternative proposal is to simply introduce `then`, however this can get a bit verbose:

```
average() by host then sum() by site
```

## Work in Progress

https://github.com/udoprog/heroic/tree/rfc-flatten-dsl

**Comment by nikek** [comment]
The more I've been thinking about it the more I like `|` (pipe). I associate pipe with "output of one operation goes into the next operation", which is what the pipe does in your proposed dsl too, right?

Also, would the parser convert the json format into this syntax or the regular chain?

**Comment by udoprog** [comment]
The JSON structure for aggregations would remain unchanged, but the JSON -> DSL conversion would prefer the flattened syntax.

So:
```
sum() | average()
```

Would be converted to:
```json
{"type": "chain", "chain": [{"type": "sum"}, {"type": "average"}]}
```

And vice-versa.

**Comment by nikek** [comment]
Very nice, go pipe!
