### ISSUE TITLE
K filters behavior?

### ISSUE THREAD

**Issue by mykolasmith** [spotify/heroic#121]
It doesn't seem like any of the K-filtering aggregations work. Regardless of the filter / k values that I use, the same sample gets returned every time. Am I using these wrong?

For example, in a set of values:

```
[
    [1, 10.0],
    [2, 20.0],
    [3, 30.0]
]
```

I would expect a query w/ `"aggregation: {"type": "abovek", "k": 25}` to only return `[3, 30.0]`. However, all points from the sample are being returned with or without the aggregation (same goes w/ bottomk, topk, and belowk).

**Comment by udoprog** [comment]
Check at the bottom of http://spotify.github.io/heroic/#!/docs/aggregations

Filtering aggregations return an entire time series, if it matches the given criteria. That is, if it has any data point witch matches it.

**Comment by mykolasmith** [comment]
@udoprog Would you consider adding another constructor property to the k filters such as "on", which takes either "series" or "point", thereby allowing to either filter out entire series matching the criteria or specific points within a series?

**Comment by udoprog** [comment]
@juruen what do you say?

**Comment by mykolasmith** [comment]
The use case I have right now is needing to sum only the positive deltas of a time series. So basically was hoping to use a chain, e.g. `delta | abovek(0) | sum`.

**Comment by juruen** [comment]
My only consideration to add this feature would be naming. Should we just have different aggregation group names that indicate that they filter time-series or points instead of using an argument?

**Comment by mykolasmith** [comment]
@juruen Yeah, that might be better. E.g. {"type": "pointsabovek", "k": 100} vs. {"type": "seriesabovek", "k": 100}.

I tried to take a stab at this using an "on" param, but couldn't get Optionals to work with the JsonProperty. Then I made it a required argument, but couldn't get the tests to pass due to an invalid argument type in LombokDataTest. If this seems like something you could implement rather quickly, would you please consider doing so?

**Comment by mykolasmith** [comment]
@juruen @udoprog we are going to hire a contractor to work on this. Do you guys have any preference on my question above? In effect, should it be its own separate aggregation or an optional argument on the existing K-filters?

**Comment by udoprog** [comment]
We currently don't have a good infrastructure to do complex decoding of the arguments in a consistent way. So my preference would currently be to just call them `pointsabove`, and `pointsbelow`. The `k` suffix doesn't add much.

**Comment by mykolasmith** [comment]
We've devised a solution for this. Pull request incoming...
