### ISSUE TITLE
Metrics not written to Metadata backend

### ISSUE THREAD

**Issue by jcabmora** [spotify/heroic#125]
Hello,

We ran into a problem where several metrics are not written to the ElasticSearch metadata backend. 

We have an openstack backend that collect metrics from several managed resources.  This causes a few hundred messages to be written to kafka almost at the same time (for our testing we are only sending one datapoint for each series to make it easier to troubleshoot).  The messages are consumed, and they are written to kafka and cassandra (the message and record count matches on both), however the number of docs created in the metadata index in elastic search does not match (verified using the `_cat/indices` ElasticSearch API).  This causes many metrics to not be available for retrieval using the query APIs.  Something that is interesting is that if we call the `query/metrics` API, the number of series returned by this call matches the number of docs in the metadata index, so we know that there is definitely a problem there.

There are no exceptions thrown by Heroic, and I added a few log statement to the `MetadataBackendKV.write()` (https://github.com/spotify/heroic/blob/master/metadata/elasticsearch/src/main/java/com/spotify/heroic/metadata/elasticsearch/MetadataBackendKV.java#L1710  method and I can confirm that all the series are processed by this method.  I increased the log level of the ElasticSearch client classes and no errors were found.

If we take those same messages and feed them to kafka by throttling the message producer (at lets say 10 per second), then all the series are written to the metadata index.  

It all seems that ElasticSearch is not able to process the requests and just drops them.  I saw in the docs that there are options `flushInterval` and `bulkActions` to configure the elasticsearch client, but by looking at the code I believe those are currently not implemented (https://github.com/spotify/heroic/blob/master/heroic-elasticsearch-utils/src/main/java/com/spotify/heroic/elasticsearch/ConnectionModule.java#L59) (please correct me if I am wrong)

After this long description, my questions are: Have you experienced a similar issue?  If so, do you have any suggestions about how to avoid this problem?  I am really not familiar with ElasticSearch, so if the answer to these questions relies on ElasticSearch knowledge, I apologize first hand.  The other question that I have, is there a way to rebuild the ElasticSearch indices from Heroic?

Thanks!

Jorge

**Comment by udoprog** [comment]
I'm thinking rate limiting of metadata ingestion kicks in.

Our current mechanism assumes that you will 'keep writing' the same metadata over and over and will drop any writes that go over a certain threshold.

The option you are looking for is `writesPerSecond` in [metadata configuration](http://spotify.github.io/heroic/#!/docs/config/metadata). Please make sure this is well above your bursts if you want all the writes to go through immediately to Elasticsearch, otherwise make sure that this value is well above your burst threshold. You might encounter ES issues at these rates, so something more clever in the consumer might be needed. Please advise what happens when you attempt this.

**Comment by jcabmora** [comment]
Thanks @udoprog for the response!   I did set the `writesPerSecond` to a very high number and  I added a log entry in the `RateLimitedCache` code to write when messages would be dropped and I made sure that we were not dropping any messages in Heroic.  I also set the `writesPerSecond` to `0` so it would use the `DisabledRateLimitedCache` and we had the same behavior.

I think that the problem relies on ElasticSearch (I saw the reference to the Jepsen blog entry).  I am thinking about implementing something on our Consumer side as you suggested to limit the rate at which metrics are sent to Ingestion.   However, I was wondering if you guys think that adding the metrics to a buffer instead of dropping them when the `writesPerSecond` policy kicks in would be a feature that you believe is valuable and possibly accept.  If so, I'd be happy to discuss with you and contribute it.

**Comment by jcabmora** [comment]
I completely agree that  a buffer will not guarantee protection against data loss in case of a crash.  

I am going to work on the buffering option, and I'll keep in mind your vision to make sure that these changes don't become a burden if later are deemed unnecessary.   I'd be interested in helping later if you decide to make the metadata writes work under the queue mechanism.

**Comment by jcabmora** [comment]
Hello!  
I ended up looking at the ElasticSearch BulkProcessor API.  I implemented that and besides helping on throughput, it has options to configure retrials.   This helped us to fix the problem we had (however we are still adding tests).  
Looking at the docs it seems that at some point there was an intention to enable bulk processing (the `concurrentBulkRequests`, `bulkActions` and `flushInterval` parameters are mentioned in the ES configuration page).  I was wondering if you guys tried this and decided not to implement for some reason.
If you are interested, I'll be more than happy to submit a PR.  
Have a good weekend, hopefully you guys get some good weather!  I'm in Northern California, and we are getting hammered with rain this weekend.

**Comment by udoprog** [comment]
Hey, that sounds cool. Yeah, we had a few bouts with the bulk processor.

I think the reasons we are currently not using it are the following:

1. Error reporting. We simply were not seeing when we were getting write errors, so we couldn't instrument it, and therefore can't alert on it.
2. Back-pressure. Even when Elasticsearch became slow, the bulk processor kept accepting writes quickly, masking the underlying problems. This coupled with not reporting errors properly meant we were mostly losing writes, and could not explain to our users why it sometimes took days for their time series to become visible.

Back pressure is typically implemented by 'holding off' resolving the future until we have acknowledge that the write associated with it has been commited. This causes the IngestionManager to run out of leases and writing processes to block.

This could have been us messing up somewhere, or maybe a newer version of the bulk processor behaves better. Overall we'd be happy to accept the patch. Just make sure to make it an optional process for now that is activated through configuration.

We're in Sweden, and at this time of the year it's a lot of darkness and snow.
I hope the weather clears up for you soon, best of luck!

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
