### ISSUE TITLE
How to delete keys

### ISSUE THREAD

**Issue by servergeeks** [spotify/heroic#132]
Hi,

For some reason I'm not able to delete keys from heroic... 
I've tried using the following curl example and it's just not doing anything.
`curl -XDELETE -H "Content-Type: application/json" http://localhost:8080/metadata/series   -d '{"filter": ["and", ["key", "key-17"], ["=", "role", "ingestor"]]}'`
 
I ended up truncating the whole table in cqlsh. Any ideas why it's not working?

**Comment by udoprog** [comment]
Deleting metadata does not delete data from C*.

We also don't have a facility for manually deleting data from C*, the recommended approach would be to use `DateTieredCompactionStrategy` and set `default_time_to_live` to how long of a retention you want to have.

Bigtable does not have the same problems as C* regarding deletions, and we are considering implementing a more flexible retention scheduler for that use case.

**Comment by zivyu** [comment]
And if you use DateTieredCompactionStrategy and set default_time_to_live , You'd better set the gc_grace_seconds=0 in C*.

**Comment by udoprog** [comment]
@zivyu good point, thanks!

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
