### ISSUE TITLE
Downsampling a range into a single value gives unexpected results

### ISSUE THREAD

**Issue by hampusohlsson** [spotify/heroic#133]
Seeing weird results when trying to do any kind of aggregation and downsample into a single value. 

For example, we're trying to get the `min/max/avg` and `stddev` over a timerange of ~5 minutes for one metric. Looking at the raw data, the values range from `[197, 199]`. In order to only get one value back, we're adding a sampling aggregation that looks like this

```js
{
  "range": {
    "type": "absolute",
    "start": 1479434197000,   
    "end": 1479434538000   // range = 341 seconds 
  },
  "aggregation": {
      "type": "spread",
      "sampling": {
        "size": "341s",
        "extent": "341s"
      }
  },
  "filter": [
    "and",
    [ "key", "foo.bar" ],
    [ "=", "tag1", "baz" ],
    [ "=", "tag2", "qux" ]
  ]
}
```

Now, the results I would expect to see, would be something like this: 
```
min = 197
avg = (sum/count) = 198.123
max = 199

stddev = 0.123
```
But instead, it gives us seemingly random values back, like below. 
```
min = 156
avg = (sum/count) = 187.123
max = 199

stddev = 17.123
```

**Findings**
- Querying for the `stddev` also yields seemingly random values.
- Bumping the timerange ±1 second sometimes gives completely different values - especially for the `min` aggregation. 
- The `max` usually is correct.
- Doing some experiments with the size and extent, the result sets does not even include the correct `min` values until you reach a pretty small size/extent.
- If we chain the spread aggregation, we actually get the correct results.

```js
...
"aggregation": {
    "type": "chain",
    "chain": [
      {
        "type": "spread",
        "sampling": {
          "size": "341s",
          "extent": "341s"
        }
      },
      {
        "type": "spread",
        "sampling": {
          "size": "1s"
          "extent": "1s"
        }
      }
    ]
  }
...
```

Perhaps I've misunderstood how the downsampling behaves, but can't really see what other options I have for getting the data.

**Comment by udoprog** [comment]
Hey!

The first thing I can think of is that a feature called `com.spotify.heroic.shift_range` is enabled by default.
This causes the range that you are querying for to be shifted according to your cadence (`341s`), so the queried for range would be rounded to 341 seconds.

You can try to disable this feature, and see if things make more sense by adding the following to your query:
```json
{
  "features": [
    "-com.spotify.heroic.shift_range"
  ]
}
```

The actual queried for range should be included in the result, see if it matches up with what you provided.

Please tell me if it still doesn't make sense.

**Comment by hampusohlsson** [comment]
That seemed to solve it, thanks for your quick reply! 

If this is an undocumented feature it might be a good idea to add a note about it in the docs :)

**Comment by udoprog** [comment]
Agreed, it's a fairly recent addition.
I've added #134 to track this.

**Comment by udoprog** [comment]
@hampusohlsson Feature flags have now been documented a bit as per #134, please have a look to see if its satisfactory. Thank you for your feedback.

**Comment by hampusohlsson** [comment]
Looks good 👍
