### ISSUE TITLE
 when I only use tags for query metrics and there are multiple keys, the return key is null.

### ISSUE THREAD

**Issue by zivyu** [spotify/heroic#138]
Today I insert four metrics , the json is 
```
{
  "series": {"key": "foo1", "tags": {"site": "lon", "host": "www.example.com"}},
  "data": {"type": "points", "data": [[1480470600000, 42.0], [1480470660000, 84.0]]}
}
```
and 
```
{
  "series": {"key": "foo2", "tags": {"site": "lon", "host": "www.example.com"}},
  "data": {"type": "points", "data": [[1480470720000, 42.0], [1480470780000, 84.0]]}
}
```
then I ues the below string for query the metric
```
{
  "range": {"end":1480470900000,"start":1480470600000,"type":"absolute"},
  "filter": ["and",["=", "site", "lon"]]
}
```
and in the response string,the key is null.
`{"range":{"start":1480470600000,"end":1480470900000},"trace":{"what":{"name":"com.spotify.heroic.CoreQueryManager#query"},"elapsed":10591,"children":[{"what":{"name":"com.spotify.heroic.cluster.LocalClusterNode#query"},"elapsed":10572,"children":[{"what":{"name":"com.spotify.heroic.metric.LocalMetricManager#query"},"elapsed":10817,"children":[]}]}]},"limits":[],"commonTags":{"site":["lon"],"host":["www.example.com"]},"result":[{"type":"points","hash":"96704091","shard":{},"cadence":0,"values":[[1480470600000,42.0],[1480470660000,84.0],[1480470720000,42.0],[1480470780000,84.0]],"key":null,"tags":{"site":"lon","host":"www.example.com"},"tagCounts":{}}],"errors":[]}`

**Comment by udoprog** [comment]
Hey, that `key` is actually different from the time series key. It is the key of the result group that is affected by things like grouping. When there is no grouping, it is intended to be `null`. Sorry for the confusion.

**Comment by zivyu** [comment]
But where is the series key in the response string?

**Comment by udoprog** [comment]
They are currently not included in the result.

Note that each result group can be made up of potentially multiple keys which means it should have a similar handling to the way that `tags` are presented, with `commonTags` in the root and `tagCounts`.

**Comment by zivyu** [comment]
thanks for your answer.
