### ISSUE TITLE
/query/metrics  limit ?

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#140]
what are the limitations ?
numbers of points returned, date ...

is it possible to paramet the number of data returned ?

thanks

**Comment by lucilecoutouly** [comment]
i have this error for long range ~ 6 month

```
{
  "range": {
    "start": 1420070400000,
    "end": 1441004460000
  },
  "trace": {
    "what": {
      "name": "com.spotify.heroic.CoreQueryManager#query"
    },
    "elapsed": 30133449,
    "children": [
      {
        "what": {
          "name": "com.spotify.heroic.CoreQueryManager#query_node"
        },
        "elapsed": 30133161,
        "children": [],
        "preAggregationSampleSize": 0,
        "numSeries": 0
      }
    ],
    "preAggregationSampleSize": 0,
    "numSeries": 0
  },
  "limits": [],
  "commonTags": {},
  "result": [],
  "errors": [
    {
      "type": "shard",
      "nodes": [
        "com.spotify.heroic.cluster.TracingClusterNodeGroup@1ef27e2f"
      ],
      "shard": {},
      "error": "Some fetches failed (81) or were cancelled (0)"
    }
  ]
}

**Comment by udoprog** [comment]
By default, each data node has a limit configured through the `metrics` sections, as described here:
http://spotify.github.io/heroic/#!/docs/config/metrics

You can disable these limits per query using query options (example below for `dataLimit`), this will be better documented soon:
```json
{
    "options": {
        "dataLimit": null
    }
}
}
```

I'm not sure if you are hitting one of these limits. Which metric backend are you using?

**Comment by lucilecoutouly** [comment]
how do you run heroic with loglevel = debug ?

**Comment by lucilecoutouly** [comment]
I have a 32 thread with 44 Go Ram 
i run cassandra 3.9  on docker for backend

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
