### ISSUE TITLE
Missing description for various properties...

### ISSUE THREAD

**Issue by servergeeks** [spotify/heroic#153]
Hi,

I can't find docs for various properties...
If someone can shed some light over the missing docs for the following would be great...
PS: Also docs updates for the updated/changed ones....

`23 known properties: "port", "corsAllowOrigin", "metrics", "suggest", "connectors", "host", "metadata", "enableCors", "shellServer", "service", "version", "cluster", "id", "features", "startTimeout", "cache", "ingestion", "analytics", "generator", "disableMetrics", "consumers", "stopTimeout", "statistics"]`

**Comment by udoprog** [comment]
Yeah, they need some docs. For now you can use [`HeroicConfig`](https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/HeroicConfig.java) a a source of truth until we get to it.

**Comment by hexedpackets** [comment]
The docs for all the parameters will be updated when we redo the example configs as part of #440.
