### ISSUE TITLE
Support detailed query logging

### ISSUE THREAD

**Issue by udoprog** [spotify/heroic#158]
This is another troubleshooting story.

We want to provide a configurable feature that gives a detailed log of how the queries are treated by heroic.

#### Suggestion

The user can provide the system with additional `clientContext` which will be included in each log step.
The system can either be provided, or will generate an `id` when the query has been received that can be used to group or correlate individual queries.

Each log line has the following structure:

```json
{
  "component": "com.spotify.heroic.query.CoreQueryManager",
  "queryId": "ed6fe51c-afba-4320-a859-a88795c15175",
  "clientContext": {
    "dashboardId": "my-system-metrics",
    "user": "udoprog"
  },
  "type": "Received",
  "data": {}
}
```

`data` would be specific to the type being logged.

In all relevant stages of query processing, a call to the query logging framework is done, which results in logging of json describing the exact structure of the query in that stage. 

Suggested relevant stages and data to log:
* **api** `Query` as received from the user, also includes relevant HTTP-based information.
* **api** `Query` as received by ClusterManager.
* **api** `FullQuery.Request` which fans out to all data nodes.
* **data** `FullQuery.Request` when received by data node.
* **data** `FullQuery` as it goes back to the API node (excluding data).
* **api** `FullQuery` as received from data node (excluding data).
* **api** `QueryTrace` with timing information for the whole query
* **api** `QueryMetricsResponse` being sent to the user (excluding data).

*Note*: All response paths excludes samples (time series data) to reduce the size of the log. This would be represented as the size of the data being returned instead.

#### Requirements

* Query logging framework is isolated from critical path of query processing in a way so that failure in the query logger doesn't affect query processing.

#### Extension to Query API

The following field would be added to the query API.

```
{
  "features": ["com.spotify.heroic.query_logging"],
  "queryLogging": {
    "queryId": "my-query-id",
    "clientContext": {
      "dashboardId": "my-system-metrics",
      "user": "udoprog"
    }
  }
}
```

This is completely optional, and query logging can be enabled globally by setting the feature flag `com.spotify.heroic.query_logging`.

#### Configuration

Query logging is configured in the configuration file under the `queryLogging` section, like the following:

```yaml
queryLogging:
  type: file
  path: /path/to/query.log
  rotationPeriod: 1d
```

Or with a logger facility:

```yaml
queryLogging:
  type: logger
  name: com.spotify.heroic.query_logging
```

**Comment by parmus** [comment]
I'd suggest that we use the explicit key ```queryId``` rather than just ```id``` to make it clear that each log entry is part of a bigger piece of information. ```id``` could be interpreted as meaning that the entry is uniquely identified by that.
Another reason for ```queryId``` is that the entries will contain multiple IDs, e.g. ```dashboardId``` so being explicit can avoid some mixups.

**Comment by parmus** [comment]
@udoprog : When we talk about "traces" in the context of this issue, do we mean traces that end up in the logs, traces that are returned to the user as part of the result, or both?

**Comment by udoprog** [comment]
@parmus this feature is currently named "log tracing" (as per `logTracing` parameter above to enable it), while the timings are just returned as "tracing".

**Comment by gabrielgerhardsson** [comment]
Would it make sense to have all of this as a part of the current query tracing functionality? The code paths and functionality seem to be very related. 

Perhaps with knobs to decide how detailed tracing we want:
* Written to logs
* Returned in query response

In other words, I'm thinking that this is not a new feature but added functionality and configurability of query tracing. What do you guys think?

**Comment by gabrielgerhardsson** [comment]
Could the following be clarified?

> Note: All response paths excludes data to reduce the size of the log. This would be represented as the size of the data being returned instead.

**Comment by gabrielgerhardsson** [comment]
+1 on the addition of allowing user to provide metadata that would be included in trace. Would it make sense to name it something more specific than "metadata"? Suggestions:
* queryMetadata
* contextualMetadata

**Comment by udoprog** [comment]
> Would it make sense to have all of this as a part of the current query tracing functionality? The code paths and functionality seem to be very related.

It is interesting, but maybe as a future improvement?
Tracing measures timings in a tree and returns it along with the response of the query. It's not inconceivable that we could attach these things to the existing tracing framework as additional information on each tree node, but the way that it is currently done would require a fair bit of refactoring to make it work.

The tracing framework could at least be unified (a little) internally to avoid duplication.

>  Returned in query response

This is interesting. Maybe add it as a secondary objective.

> Could the following be clarified?

It simply means that the return path contains a lot of samples - time series data that should be shipped to the user. This is too much to include when logging information to a third party system.
I've added more clarification for it.

> +1 on the addition of allowing user to provide metadata that would be included in trace. Would it make sense to name it something more specific than "metadata"? Suggestions:

I think it is implied by the context since it's part of `logTracing.metadata` and more information would seem redundant. Is this fine for you?

**Comment by gabrielgerhardsson** [comment]
> It is interesting, but maybe as a future improvement?
> Tracing measures timings in a tree and returns it along with the response of the query. It's not inconceivable that we could attach these things to the existing tracing framework as additional information on each tree node, but the way that it is currently done would require a fair bit of refactoring to make it work.
> 
> The tracing framework could at least be unified (a little) internally to avoid duplication.

Ok!

> > Returned in query response
> This is interesting. Maybe add it as a secondary objective.

Cool

> It simply means that the return path contains a lot of samples - time series data that should be shipped to the user. This is too much to include when logging information to a third party system.
> I've added more clarification for it.
Ah yes, totally :)

> > +1 on the addition of allowing user to provide metadata that would be included in trace. Would it make sense to name it something more specific than "metadata"? Suggestions:
> I think it is implied by the context since it's part of logTracing.metadata and more information would seem redundant. Is this fine for you?
Ok, yep I'm fine with that.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
