### ISSUE TITLE
Support reproducing logged queries

### ISSUE THREAD

**Issue by udoprog** [spotify/heroic#159]
As queries are being logged it should be easy to reproduce the query.

The biggest obstacle currently is that relative ranges should be resolved into absolute ones. This is potentially related to #158, but means that it should be easy to reproduce logged queries.

A new endpoint could be introduced that allows one to 'execute' queries in the same state as they are logged.

Other considerations include:

* Fan out to the same set of nodes as before.
* Exclude data which did not exist when the query was sent.

**Comment by parmus** [comment]
LGTM. I would potentially split the other considerations into a different issue to keep the scope smaller. Adding the resolved absolute range to a log or even the result itself is a small task. Controlling the fan out and filtering data based on write time is a bit bigger change.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
