### ISSUE TITLE
DSE and SOLR support

### ISSUE THREAD

**Issue by wendelicious** [spotify/heroic#16]
DSE now supports SOLR indexing pretty much out of the box.  Does Heroic have plans to use this behavior natively?  Or is ElasticSearch the only game in town for this?

**Comment by udoprog** [comment]
Thanks for the tip!

So far we don't have any plans of building support for an alternative to Elasticsearch.
But DSE SOLR on paper looks like a really good candidate for metadata and suggestions. Do you have any experience with it?

I'll leave this open in-case someone wants to pick it up in the future.
