### ISSUE TITLE
Meaningful Metrics

### ISSUE THREAD

**Issue by udoprog** [spotify/heroic#174]
This change proposes to introduce more structure into existing time series that shows which tags that indicate what a time series _means_.

The goal is to provide more metadata to users of the system of what is the makeup of a valid time series.
This metadata will be defined by metric collectors in the form of a `scope`.

branch: https://github.com/udoprog/heroic/tree/meaningful-metrics

Testing the branch can be done through the following:

```bash
$> mvn package -D findbugs.skip=true -D checkstyle.skip=true -D maven.test.skip=true
$> tools/heroic-shell -P memory -P generator --server
heroic> load-generated
heroic> metadata-find-series $scope(what=teleported-goats)
```

#### Suggestion

Existing time series **A** look like the following:

```json
{
  "key": "system",
  "tags": {
    "host": "database.example.com",
    "role": "database",
    "what": "disk-used",
    "unit": "%",
    "mountpoint": "/"
  }
}
```

This proposes the introduction of the `scope` field:

```
{
  "scope": ["what", "unit"]
}
```

What this indicates is that only time series which have the same scope are the same, and can be compared to each other.

Assume there is another time series **B** that looks like this:

```json
{
  "key": "system",
  "tags": {
    "host": "database.example.com",
    "role": "database",
    "what": "disk-used",
    "unit": "Mb",
    "mountpoint": "/"
  },
  "scope": ["what", "unit"]
}
```

The scope structures for **A** and **B** are as follows:

```json
A: {"what": "disk-used", "unit": "%"}
B: {"what": "disk-used", "unit": "Mb"}
```

This indicates that they are _not_ compatible. The reasoning being that they have different units.

#### scope filter

Along this, a new filter will be defined:

```
JSON: ["scope", [[<key>, <value>], ...]]
HQL: $scope(<key>=<value>, ...)
```

This allows queries only include series which have strictly the same scope structure.

#### scope suggestions

A new endpoint will be introduced:

```
POST: /metadata/suggest-scope
```

Request:

```json
{
    "filter": ["=", "what", "disk-used"]
}
```

Note: **filter** has the same structure as other filters.

Response:

```json
{
    "result": [
        {"what": "disk-used", "unit": "%"},
        {"what": "disk-used", "unit": "Mb"}
    ]
}
```

#### API addition

The response data structure will contain a `.scopes` field.

```
{
    "scopes": [
        {"what": "disk-used", "unit": "%"},
        {"what": "disk-used", "unit": "Mb"}
    ]
}
```

This will allow a UI to determine if the result contains 'non-overlapping' results.

#### General

On top of scopes, we can build the following:

* In a given query, one may only fetch data for a single scope structure at a given time.
* In a given query, one may only aggregate over a single scope structure at a given time.
* Suggestions for scopes, giving users a better overview of what a 'proper' time series looks like.

**Comment by mykolasmith** [comment]
The end goal (e.g. to aggregate over a single meaning for a given time) would certainly be useful, although I would question the necessity of having a predefined meaning tag. Wouldn't it be more useful to enhance the aggregation engine sufficiently that those parameters could be passed into the query at runtime?

**Comment by udoprog** [comment]
@mykolasmith thanks for your feedback. this rfc is still work-in-progress, the query engine (specifically filtering) will indeed have to be extended to support this.

**Comment by udoprog** [comment]
Changed `meaning` to `scope`.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
