### ISSUE TITLE
Heroic Shell Leading Space

### ISSUE THREAD

**Issue by PseudoSky** [spotify/heroic#18]
Might be good to trim the commands from the shell

<img width="699" alt="screen shot 2016-01-09 at 5 34 36 pm" src="https://cloud.githubusercontent.com/assets/3356993/12218753/a3ad3bac-b6f6-11e5-916e-81e19cc7ebb7.png">

**Comment by udoprog** [comment]
For anyone who wants to have a stab at this, the following is most likely the best place to put it in:

**Comment by PseudoSky** [comment]
Pull Request #20 

I was going to add a test case, but I wasn't positive on how the syntax of QuoteParserTest works.

Would this work?

```
test(Case.of("  trimming_spaces  ", "trimming_spaces"));
```
