### ISSUE TITLE
Cannot see/select data passed the beggining of the new year.

### ISSUE THREAD

**Issue by valentinul** [spotify/heroic#180]
Hello & Happy new year! 

How to better start the new year than with a bug ? :)

It seems that data is not being show/selected past the beginning of the new year... So in this case 1/1/2017.
Any ideas why? 

I have data in my cluster since (Thu 22 Dec 2016). I can see the timestamp in ES so I'm guessing it could be something with the grafana/grafana plugin ? 
BTW: that plugin could maybe get more love...seems. And also what do you guys use for graphing data from heroic api? 

Thanks!

**Comment by valentinul** [comment]
Hi,

I was to fast to pull the trigger...seems to be my mistake. I was using points(1d) and data was selected only for 1 day.

**Comment by udoprog** [comment]
ok, thanks!
