### ISSUE TITLE
OSX Problems

### ISSUE THREAD

**Issue by PseudoSky** [spotify/heroic#19]
Config
---------
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

Still in the process of getting this to actually run, but preliminary findings

Homebrew Cassandra (V2.0 & V3.X) don't work with this 

I have gotten the config to work (I think) with cassandra from the apache repo
`apache-cassandra-2.1.12`

Errors 
---------
`java -cp heroic-dist/target/heroic-dist-0.0.1-SNAPSHOT-shaded.jar com.spotify.heroic.HeroicService heo.yaml`

Still having problems with elasticsearch 

From the heroic shell
<img width="767" alt="screen shot 2016-01-09 at 5 42 10 pm" src="https://cloud.githubusercontent.com/assets/3356993/12218806/cb48746e-b6f7-11e5-9ee6-f15e6658dc36.png">

From the elasticsearch shell
<img width="690" alt="screen shot 2016-01-09 at 5 42 39 pm" src="https://cloud.githubusercontent.com/assets/3356993/12218811/e68e9ca8-b6f7-11e5-9df5-6880235c8071.png">

**Comment by udoprog** [comment]
Hey.

I'll look into what the compatibility promise is for the datastax driver. My hunch is that minor version changes _should_ work, but I have to verify.

Which Elasticsearch version are you running against?

**Comment by PseudoSky** [comment]
Same results on elasticsearch versions
`Version: 2.0.0, Build: de54438/2015-10-22T08:09:48Z, JVM: 1.8.0_45`
`Version: 2.1.1, Build: 40e2c53/2015-12-15T13:05:55Z, JVM: 1.8.0_45`
Could it be JVM: 1.8.0_45?

Error logs from heroic and elasticsearch, config, and version info

https://gist.github.com/PseudoSky/8bf41c29d51a849cd3b1

**Comment by swps** [comment]
For the sake of time, are there known version-compatible combinations of all the products (Kafka, Cassandra, ElasticSearch) I can start with?

**Comment by udoprog** [comment]
I've used the following combinations successfully:
* C* 2.0-2.1
* Elasticsearch 1.4.x, 1.7.x
* Kafka 0.8.2.2

I've also raised the following issue with Elasticsearch regarding mixed version clusters, since 2.x clients are not compatible with 1.x:
https://github.com/elastic/elasticsearch/issues/13273
