### ISSUE TITLE
Differences between various selectors.

### ISSUE THREAD

**Issue by servergeeks** [spotify/heroic#190]
Hi,
I have various graphs using queries like the following:
```
average(5m) by host from points where type=epp_connections
### or ###
average(5m) by host from points(1d) where type=epp_connections
```

I have a couple of questions regarding **points** and **size**

1. Whats the difference between points and points(1d). 

2. Is there any speed/performance advantage ?

3. **Issue**? When using points(1d) the graph fails to update from time to time 
    More exact, the points don't get pulled/graphed after a certain point in time.
   So for example I start with a time window of 6 hours and then I zoom out. 

4. Whats the difference between using something like average(5m) and average.... with size=5m ? 

~~5. Can I have alias defined in grafana to avoid showing the full queries in the legend/hover ?
    For example showing, a result like -> `{database: "PROD", host: "ursa1.cc", type: "epp_connections"} `as  **PROD1** in the legend/hover/table etc...~~ found how to do it..

Thank you!

**Comment by udoprog** [comment]
> Whats the difference between points and points(1d)
If you are using the Grafana plugin, then the interval is calculated automatically for you. By using `1d` you are specifying that you only want one day (relative from now) worth of data.

> Is there any speed/performance advantage ?
No, but you will be querying for a larger interval if grafana is configured for more than one day.

> Issue? When using points(1d) the graph fails to update from time to time
More exact, the points don't get pulled/graphed after a certain point in time.
So for example I start with a time window of 6 hours and then I zoom out.
Not sure about this, screenshot?

> Whats the difference between using something like average(5m) and average.... with size=5m?
I believe they are the same, but the second form is more explicit. But it should not be possible to mix them.

**Comment by hexedpackets** [comment]
Closing in favor of #238.
