### ISSUE TITLE
Poor read performance - which is Bottleneck : elasticsearch , cassandra or heroic

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#198]
to increase read performance i want to know which is the Bottleneck 

* elasticsearch
* cassandra
* heroic 

which of this have  i to get more cpu or ram ?

i work on a single node made of docker 
single node elasticsearch
single node cassandra
single read heoic

help is apriciate

thanks
Lucile

**Comment by udoprog** [comment]
It greatly depends on their relative configuration, any one can be a bottleneck.

What we generally observe however, is that fetching metrics (i.e. loading them from Bigtable/Cassandra) is what takes up the bulk amount of time. And is dependent on how much data you intend to load. Generally the number of time series loaded, and the range of the query.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
