### ISSUE TITLE
Heroic in Docker

### ISSUE THREAD

**Issue by wendelicious** [spotify/heroic#21]
Do you have a Docker image running heroic to make setting up development a little easier?  Or do you have a dockerfile which I can use to create my own with all the dependencies and such?

**Comment by udoprog** [comment]
No, no Dockerfile yet. Development has been fairly straight forward since the project is pure Java.

What would you like to see?

**Comment by raks81** [comment]
Looks like this has since been [added](https://github.com/spotify/heroic/blob/master/Dockerfile).

**Comment by dmichel1** [comment]
@raks81 it has! let us know if you have any issues using the docker image.
