### ISSUE TITLE
Productionization Guidance

### ISSUE THREAD

**Issue by mykolasmith** [spotify/heroic#215]
Hi,

We've been running Heroic in production for some time now and are beginning to ramp up I/O steadily. Looking forward, I'm wondering if there's any guidance that exists about how to most effectively use Heroic in a production environment. What knobs do you recommend turning on JVM to achieve the best read/write throughput? Do you recommend using certain nodes as read-only and others as write-only?

We're using Big Table for the data backend and Elasticsearch for metadata. We use the HTTP API for all read/write functionality. Most of our transactions are for a single data point going into a single series. I have considered implementing batching on our producers, but for now each data point is written in a single HTTP request. I'm thinking about doing the following setup. Can you please let me know if this sounds reasonable and if so, which parameters to tweak in order to achieve the desired outcomes?

- 3x API nodes (high CPU, low memory), write only. Needs to be able to handle a bunch of concurrent HTTP connections with smaller payloads.
- 3x API nodes (med CPU, high mem), read only. Needs to be able to handle fewer HTTP connections, with much higher IO per request.

What JVM or Heroic config options would each type of machine be best equipped with? How can each of these node types be optimized for their respective role?

Thanks!

**Comment by valentinul** [comment]
I'm not sure if there exist any guidance on how to use most effectively Heroic but I can share my current setup.

The end goal would be to use heroic + cassandra for storing metrics without any time limitation. Yep, forever.

Current setup runs on 20 Vmware vms. 

5 cassandra nodes => 4 cpus, 16 gb ram per node
6 elasticsearch nodes => 4 cpus, 16 gb ram per node, 3 nodes for metadata, 3 nodes for suggestions.
4 heroic nodes => 4 cpus, 4 gb ram per node
1 grafana vm => 2 cpus, 4 gb ram.
3 kafka servers => 4 cpus, 8 gb ram per node.
1 logstash vm => 8 cpus, 20 gb ram.

Currently consuming circa 1 GB of data per day and everything runs pretty stable. 
The amount of data generated for metrics will increase when I'll migrate all the graphs from a cacti instance but I hope heroic will remain usable/stable when everything will be migrated.

If you have any question let me know.

All the best,
Valentin
