### ISSUE TITLE
Disable listing all possible series in grafana when creating a new graph

### ISSUE THREAD

**Issue by valentinul** [spotify/heroic#220]
Hi,

Can someone update the grafana plugin so it doesn't shows/selects all possible series when you create a new graph and there is no query specified ? 

This is essentially blocking the current browser tab and probably stressing the heroic api without any proper reason.

**Comment by udoprog** [comment]
Hey,

The datasource is not officially supported, but a hack put together by me here:
https://github.com/udoprog/udoprog-heroic-datasource

I'd suggest opening an issue there, and I'll see if I can find some time to look into it. But contributions are also highly welcome.
