### ISSUE TITLE
HTTP Client Configuration Still Available?

### ISSUE THREAD

**Issue by mykolasmith** [spotify/heroic#232]
Hi,

I noticed [here](https://github.com/spotify/heroic/blob/master/docs/heroic.example.yml#L177) that there is a configuration profile for `client`, that has options such as: `connectTimeout` and `queueSize`. I can't find any mention of these options in the codebase, so I'm wondering if the `client` directive is still supported for configuring the HTTP API.

Thanks!

**Comment by udoprog** [comment]
Hey,

No, client configuration is not available. We used to do RPC using http clients, but no longer. So these options are no longer relevant to my knowledge!

**Comment by mykolasmith** [comment]
Thanks @udoprog.

Is there any configuration available to tune the HTTP API (Jetty)? I ask because we're seeing quite a few `/write` operations timing out under heavy load, even though the box running Heroic never exceeds ~10% CPU load. Seems like we're leaving some performance on the table here and would like to jack up the # of workers available to service requests on each box.

**Comment by udoprog** [comment]
Yeah you're right. Deserializing the request would happen somewhere in Jetty, and whatever thread pool they configure by default. For ingestion this can easily be a bottleneck.

So server currently doesn't have a dedicated configuration section, but it could use one. For now we can look at how an option like `enableCors` is being propagated [HeroicConfig](https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/HeroicConfig.java#L102) and do something similar. The server itself is being setup in [HttpServer](https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/http/HttpServer.java#L141)

**Comment by mykolasmith** [comment]
Great, I'll look into the changes required to enable Jetty configuration in `heroic.yml`. Would you want it to be a top-level directive (as is the case with `port`), or a separate section in the configuration (e.g. `http:`)?

**Comment by udoprog** [comment]
Hm, top level ones are probably getting too crowded.

I can imagine that there are a fair amount of things that will be added by this. So please add another section if you end up taking a look.

**Comment by mykolasmith** [comment]
FWIW, we moved our consumers to Kafka rather than POST to /write. We will no longer be needing this feature. Feel free to close this issue.

**Comment by udoprog** [comment]
@mykolasmith cool

There are a few things in the works intended to give more configurability for the Server. Hopefully that will improve the situation for future users.
