### ISSUE TITLE
Configuration docs for Bigtable

### ISSUE THREAD

**Issue by mbrukman** [spotify/heroic#237]
https://spotify.github.io/heroic/#!/docs/getting_started/configuration needs to include instructions for how to configure Heroic to connect to Bigtable as a backend.

**Comment by Fjsmoreira** [comment]
Would be of Great help to have this one!

**Comment by udoprog** [comment]
I've added a section in:
http://spotify.github.io/heroic/#!/docs/config/metrics#google-bigtable

As well as a mention in:
https://spotify.github.io/heroic/#!/docs/getting_started/configuration#bigtable

I hope this is helpful. Improvement suggestions are welcome.

**Comment by mbrukman** [comment]
Looks great! Thanks, @udoprog!
