### ISSUE TITLE
Document how to visualize data in Heroic

### ISSUE THREAD

**Issue by mbrukman** [spotify/heroic#238]
Looking at https://spotify.github.io/heroic/#!/index or even https://spotify.github.io/heroic/#!/docs/overview it's hard to tell what graphic frontend a user can run in front of Heroic to create dashboards and visualize the metric data that Heroic is storing.

If there is a visualization service that Heroic ships with, or if it integrates with external visualization/dashboarding tools such as Grafana, that should be documented such that it's clear it's not only an API service.

**Comment by valentinul** [comment]
Hi,
In my case we use grafana for now but also started writting a custom interface based on d3 + vuejs.

**Comment by jsferrei** [comment]
@dmichel1 All for it. Let's first have someone go through a fresh install and see if https://github.com/spotify/heroic-grafana-datasource/blob/master/README.md covers everything.

**Comment by lmuhlha** [comment]
https://github.com/spotify/heroic/pull/565
