### ISSUE TITLE
Publish a list of production users and case studies

### ISSUE THREAD

**Issue by mbrukman** [spotify/heroic#239]
Potential users evaluating adoption of new technology are typically curious as to who else is using the product (particularly in production), what their use cases / scale are, and what their experience has been.

To make users more comfortable to adopt Heroic, it would benefit from having a page listing who already uses Heroic in production, even if it's just the company logo (assuming they're OK with both a public disclosure plus their logo being used) and even better, if they could provide either a short description of how they're using it or a more in-depth case study (the length of a typical blog post).

Here are some examples of how other projects do this:

* Apache Cassandra: http://cassandra.apache.org/ and https://en.wikipedia.org/wiki/Apache_Cassandra#Prominent_users
* Apache HBase: http://hbase.apache.org/poweredbyhbase.html
* KairosDB: http://kairosdb.github.io/ (see bottom of page)
* MongoDB: https://www.mongodb.com/community/deployments
* Vertx: http://vertx.io/whos_using/

**Comment by mykolasmith** [comment]
Feel free to add [Oden Technologies](https://oden.io/)

![logo-transparent-black](https://cloud.githubusercontent.com/assets/1483054/24464039/a87dbd30-1476-11e7-8a14-bd33a3899d2f.png)

**Comment by skateordie** [comment]
@mbrukman great point, thanks for the suggestion! 💯 

@mykolasmith is Oden Technologies still using Heroic? If so, can you provide some info on your scale and use cases? Thanks

**Comment by mykolasmith** [comment]
cc/ @jamesmaidment
