### ISSUE TITLE
Heroic Java Client

### ISSUE THREAD

**Issue by dmichel1** [spotify/heroic#245]
Hello,

Are there any plans to create a Heroic Java Client? 

Maybe at a minimum the heroic artifacts can be uploaded to a maven repo? It would be awesome if I could import the value objects in `heroic-component`. 

Thanks,
Drew

**Comment by hexedpackets** [comment]
Doing this without duplicating code will require decoupling all of the modules.

**Comment by hexedpackets** [comment]
The initial client shouldn't be concerned with ingestion at all, it should just be used for querying Heroic.

**Comment by dmichel1** [comment]
Closed by https://github.com/spotify/heroic-client-java
