### ISSUE TITLE
Enable Gzip?

### ISSUE THREAD

**Issue by mykolasmith** [spotify/heroic#255]
Would it be possible to enable gzip compression for responses coming from the Heroic HTTP API?

EDIT: I tried adding /etc/jetty-gzip.xml and the changes didn't seem to be picked up. Same with /etc/jetty.xml when trying to increase maxThreads for the ThreadPool. Where are the HTTP API Jetty settings being set? This is in relation to: https://github.com/spotify/heroic/issues/232

**Comment by udoprog** [comment]
Hey, why did you close this @mykolasmith?

**Comment by mykolasmith** [comment]
Because it's essentially a duplicate of my other issue (https://github.com/spotify/heroic/issues/232).

**Comment by mykolasmith** [comment]
Fixed by https://github.com/spotify/heroic/pull/285
