### ISSUE TITLE
date range query/metrics

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#262]
Hello ,
I make  some request in my heroic database wich store 1 year datas
but i encounter a strange thing:

if i request /query/metrics upon a range of 1 month i get my datas back ( everything ok)
if i request by /query/metrics the same query except the date range that is now 2 months i get no data in return
it's really desapointing, it's odd 
i should receive back at least all the data i receive in the first query, that is to say : data over 1 month 

how can i fix it ???

thanks

**Comment by udoprog** [comment]
What does the response contain (without any potential data). I'm guessing you are hitting a quota, which should be visible in the response, and can be raised.

**Comment by lucilecoutouly** [comment]
i thought i was hitting a quota but i don't know how to manage it :

` curl -X POST   http://localhost:8080/query/metrics   -H 'cache-control: no-cache'   -H 'content-type: application/json'   -H 'postman-token: 5ea755d5-955d-3c48-e4e5-05bb28ec2a80'   -d '{"source": "points", "range": {"type": "absolute", "start": 1012005540000, "end": 1041032340000}, "aggregation": {"type": "group", "of": ["f"], "each": {"type": "max", "size": {"duration": 4, "unit": "MINUTES"}}}, "filter": ["and", ["key", "nsa"], ["=", "g", "rt"], ["=", "n", "5"],  ["~", "f", "31.{8}"]]}'

{"range":{"start":1012005360000,"end":1041032160000},"trace":{"what":{"name":"com.spotify.heroic.CoreQueryManager#query"},"elapsed":200688997,"children":[{"what":{"name":"com.spotify.heroic.CoreQueryManager#query_node"},"elapsed":200685452,"children":[]}]},"limits":[],"commonTags":{},"result":[],"errors":[{"type":"shard","nodes":["com.spotify.heroic.cluster.TracingClusterNode$Group@79d8b8dd"],"shard":{"site":"nsadb"},"error":"Some fetches failed (54) or were cancelled (0)"}]}

` 
have i to add in the query some options : 

`"options":{
		"fetchSize":10000,
		"dataLimit":10000,
		"tracing":true,
		"failOnLimits": false,
		"groupLimit":10000,
		"seriesLimit":10000
	},`

**Comment by udoprog** [comment]
Assuming you are running master (See #243 this for why), can you paste the logs emitted by the service during one of these queries?

**Comment by lucilecoutouly** [comment]
i want to have debug trace 
i try:
`bin/java -Deu.toolchain.async.Managed.trace=yes -Dloglevel=TRACE -cp heroic-dist/target/heroic-dist-0.0.1-SNAPSHOT-shaded.jar com.spotify.heroic.HeroicService heroic.yml`

but i only have INFO
how to have debug ???

**Comment by udoprog** [comment]
You follow the instructions on https://github.com/spotify/heroic#logging - specifically you'll have to copy and modify https://github.com/spotify/heroic/blob/master/docs/log4j2-file.xml to suit your needs.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
