### ISSUE TITLE
Make a query for a fully qualified tags, bypassing the lookup service

### ISSUE THREAD

**Issue by Xeago** [spotify/heroic#264]
There's currently a limitation that for 'unknown' timeseries, they cannot be queried. Could we augment the querying API to allow the notion of a fully qualified query, where the user has specified all tags for a set of timeseries. This is very useful when referring to specific points in the past, referenced from documentation for incident scenarion's.

**Comment by udoprog** [comment]
This is also something we've discussed as a means to harden systems against metadata unavailability. The client can periodically request a list of identifiers based on a filter that can be used for querying. It also would work as a way to freeze the state of a query in time, making the result more reproducable.
