### ISSUE TITLE
hack json response : format

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#266]
Hey,

I need a json response from Heroic with a different format because it will be faster to parse.

i need something like : 
```

{
…,
result:
[
{timestamp: xxx,value: xxx, tag1:xxx,...}
]

}
```

could you help me find which files in the code i need to hack ...
which files are impact

thanks

**Comment by udoprog** [comment]
The model used to serialize the response is converted to here:
https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/http/query/QueryResource.java#L181

You can find the model, and it's serializer here:
https://github.com/spotify/heroic/blob/master/heroic-component/src/main/java/com/spotify/heroic/metric/QueryMetricsResponse.java

Each different data type also have their own serializers, which are currently not configurable, example below is `Point`:
https://github.com/spotify/heroic/blob/master/heroic-loading/src/main/java/com/spotify/heroic/metric/PointSerialization.java

This is where the serializer for point is being configured:
https://github.com/spotify/heroic/blob/master/heroic-loading/src/main/java/com/spotify/heroic/HeroicMappers.java

**Comment by lucilecoutouly** [comment]
thanks,
so i am trying to write some code but i am really new to java 
QueryHeatmapResponse.java (hack from QueryMetricResponse.java)

`private void serializeResult(
            final JsonGenerator g, final Map<String, SortedSet<String>> common,
            final List<ShardedResultGroup> result
        ) throws IOException {

            g.writeStartArray();

            for (final ShardedResultGroup group : result) {
                g.writeStartObject();

                final MetricCollection collection = group.getMetrics();
                final SeriesValues series = SeriesValues.fromSeries(group.getSeries().iterator());

                //g.writeStringField("type", collection.getType().identifier());
                //g.writeStringField("hash", Integer.toHexString(group.hashCode()));
                //g.writeObjectField("shard", group.getShard());
                //g.writeNumberField("cadence", group.getCadence());
                g.writeObjectField("values", collection.getData());
                for (final List data : collection.getData() ) {



                    g.writeStringField("timestamp",data.timestamp );
                    g.writeStringField("value",data.value );
                }
                writeKey(g, series.getKeys());
                writeTags(g, common, series.getTags());
                //writeTagCounts(g, series.getTags());

                //g.writeStringField("key", series.getKeys().iterator().next());
                g.writeEndObject();
            }

            g.writeEndArray();
        }` 
 
i don't know how to itterate over  collection.getData() ?

**Comment by lucilecoutouly** [comment]
so i write : 
```java
 private void serializeResult(
            final JsonGenerator g, final Map<String, SortedSet<String>> common,
            final List<ShardedResultGroup> result
        ) throws IOException {

            g.writeStartArray();

            for (final ShardedResultGroup group : result) {
                g.writeStartObject();

                final MetricCollection collection = group.getMetrics();
                final SeriesValues series = SeriesValues.fromSeries(group.getSeries().iterator());

                //g.writeStringField("type", collection.getType().identifier());
                //g.writeStringField("hash", Integer.toHexString(group.hashCode()));
                //g.writeObjectField("shard", group.getShard());
                //g.writeNumberField("cadence", group.getCadence());
                //g.writeObjectField("values", collection.getData());
                if (collection.getType() == MetricType.POINT) {
                    final List<Point> points= collection.getDataAs(Point.class);

                        for (final Point p :points){
                            String strLong = Long.toString(p.getTimestamp());
                            String strDouble = Double.toString(p.getValue());
                            g.writeStringField("timestamp", strLong);
                            g.writeStringField("value",strDouble );
                            writeKey(g, series.getKeys());
                            writeTags(g, common, series.getTags());
                        }
                }
                //writeKey(g, series.getKeys());
                //writeTags(g, common, series.getTags());
                //writeTagCounts(g, series.getTags());

                //g.writeStringField("key", series.getKeys().iterator().next());
                g.writeEndObject();
            }

            g.writeEndArray();
        }
```

**Comment by lucilecoutouly** [comment]
i am trying to format render response from class RenderResource

but i don't understand what are query params  **backendGroup** ?

```java

@QueryParam("q") String queryString, 
@QueryParam("backend") String backendGroup,
@QueryParam("title") String title, 
@QueryParam("width") Integer width,
@QueryParam("height") Integer height, 
@QueryParam("highlight") String highlightRaw,
@QueryParam("threshold") Double threshold
```

**Comment by udoprog** [comment]
You can have multiple backends configured (it's a list), each belonging to a group. That parameter allows you to select one.

**Comment by valentinul** [comment]
@lucilecoutouly you could use logstash... 
In my case I put everything into a kafka queue and crunck on data data from there with logstash ...

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
