### ISSUE TITLE
Heroic internal metrics

### ISSUE THREAD

**Issue by berupp** [spotify/heroic#272]
Hi,

I was wondering how to access the heroic internal metrics. If have gone through the code a bit and see that codahale is used. I found the FastForwardReporter that seems to be sending metrics to port 19091. 

However, I don't know how to activate the internal metrics and how I could view/access them. 

Any pointers are highly appreciated

Thanks in advance

Ben

**Comment by udoprog** [comment]
Hey,

Metrics are enabled as a configuration option.
The implementation is modular, but there is only one type available right now: [`statistics/semantic`](https://github.com/spotify/heroic/tree/master/statistics/semantic).

Statistics is enabled using the following configuration:
```yaml
statistics:
  type: semantic
```
This would result in metrics being pushed to a local [ffwd](https://github.com/spotify/ffwd) agent.

There currently aren't any configuration options available for semantic metrics, but if some where to be added, they would be added here:
https://github.com/spotify/heroic/blob/master/statistics/semantic/src/main/java/com/spotify/heroic/statistics/semantic/SemanticStatisticsModule.java#L46

Any additional methods for pushing statistics would have to be built as a new statistics module (e.g. [dropwizard metrics](http://metrics.dropwizard.io/)).

We'd be happy to help out if this is something that you would want to do!

**Comment by berupp** [comment]
Thanks, enabling statistics was the first step.

I would like to send the internal metrics (statistics) to our graphite/grafana container, so I can create a comprehensive dashboard with all the information I need for some performance testing.

I'm thinking to add another module with a GraphiteReporter. I'd need to create an adapter for the SemanticMetricRegistry, and add a way to provide the graphite IP via `heroic.yaml`.

If you can think of an easier way to get the heroic internal metrics into graphite, I'd be grateful for hints. I am not sure how to get the semantic metrics out of that ffwd agent.

**Comment by udoprog** [comment]
No, sorry. We don't have graphite support for ffwd either. You'll have to write another reporter or an output plugin for ffwd.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
