### ISSUE TITLE
Metadata Rebuild

### ISSUE THREAD

**Issue by jcabmora** [spotify/heroic#273]
Hello,

I am working on way to rebuild the Metadata in ES by adding a new ShellTask.

The basic idea is to be able to fetch metrics from cassandra, using filtering so we do not have to rebuild all the history if it is not needed, and then process them through the metadata/suggest backend(s).

Is there a way to fetch data from cassandra based on a timestamp?  For example, get all the keys that have been added in the last 30 days? 

I tried looking at how the  `data-migrate` and `keys` ShellTasks work, and they provide functionality  to allow filtering based on the `token(metric_key)`, but if I am not missing something (which I definitely can because I am not super familiar with Cassandra), I believe that will only serve for paging purposes, and the data is not guaranteed to be sorted by timestamp.

Thanks!

**Comment by jcabmora** [comment]
Never mind my question, I now know the answer is "It can't be done", so the only option is to do a full scan of the metrics table.

**Comment by udoprog** [comment]
Hey,

We have _a lot_ of keys, and rebuilding an index from them is not inconceivable. Iterating over all available keys can be fast enough.

If you want a faster solution, the following would be doable:
It would be possible to build a metadata-backend based on Cassandra, plug it into the existing indexing process and then make use of a custom metadata-migration task when you want to rapidly rebuild your Elasticsearch indexes.

A Cassandra-based index would not be used as a real metadata-backend, only for storage. It would not be possible to drive queries unless the dataset is tiny.

Another detail is that rapid indexing towards Elasticsearch is best accomplished by disabling background indexing, writing a batch, and re-enabling it. We are currently also testing Elasticsearch 5.x internally, which will be released soon. And that should have a more efficient bulk API.

**Comment by mykolasmith** [comment]
Incidentally, I am also working on a means of doing this, but by generating a spec of all "known" series (e.g. all possible key & tag combinations) and rebuilding the ElasticSearch indexes manually.  Fwiw, our solution uses BigTable, but I haven't yet found a way of linking the existing series IDs to the metadata. 

Something that does this automatically would be super useful to being able to Heroic data resiliency (since right now, we're relying on backing up Elasticsearch manually, which is pretty sketchy in ES1.7)

**Comment by jcabmora** [comment]
Thank you guys for the responses.   I am going to put something together and I'll share it.  If you think it is worth to push upstream I'd be happy to do.
