### ISSUE TITLE
Single (Non-Rotating) Index Butchers Series Keys

### ISSUE THREAD

**Issue by mykolasmith** [spotify/heroic#279]
Hi,

We use UUID4 strings as our timeseries keys, e.g. `d079ec3d-fb72-4dde-a851-f884abf8b8e2`

Two changes have occurred in our QA environment:
1) We switched our Elasticsearch backend from a rotating index to a single index.
2) We bumped the Heroic build to master.

This has resulted in the following behavior when we query `http://heroic/metadata/keys`
POST -> `{}`

```
{
  "errors": [],
  "keys": [
    "16e2f4cdd9cc",
    "1abca82a",
    "dd981b46",
    "4dde",              <---------- part 3
    "4f64",
    "464d",
    "8164",
    "0f6d3abb6da8",
    "f884abf8b8e2",    <--------- part 5
    "d079ec3d",           <--------- part 1
    "8aaa",
    "457c",
    "600",
    "fb72",        <--------- part 2
    "5402",
    "60",
    "a851"        <--------- part 4
  ],
  "size": 17,
  "duplicates": 51
}
```

d079ec3d + fb72 + 4dde + a851 + f884abf8b8e2 = `d079ec3d-fb72-4dde-a851-f884abf8b8e2`

As you can see, the above mentioned UUID4 key has been split along the dashes into individual keys. What gives? This must be a recent regression, as our production cluster is not behaving as such. Raw metadata looks OK in Elasticsearch, so it must be how Heroic is interpreting it...

**Comment by mykolasmith** [comment]
When I query Elasticsearch directly, you can see that the document is intact, as expected:

GET -> `http://elasticsearch/heroic/_search`

```
{
        "_index": "heroic",
        "_type": "metadata",
        "_id": "dd53e84fc0e78ea5f22d55ee406e6039",
        "_score": 1,
        "_source": {
          "key": "d079ec3d-fb72-4dde-a851-f884abf8b8e2",
          "tags": [
            "metric\u0000zonetemp"
          ],
          "tag_keys": [
            "metric"
          ]
        }
      }
```

**Comment by mykolasmith** [comment]
POST -> `http://heroic/query/metrics`

```{  
   "range":{  
      "type":"relative",
      "unit": "MINUTES",
      "value": 1
   }
}```

If I do an unfiltered query of the last minute of data, the results are shown, except the key is null. Something is very wrong here!

```    {
      "type": "points",
      "hash": "531f5152",
      "shard": {
        "site": "us-east1"
      },
      "cadence": 0,
      "values": [
        [
          1495230840000,
          346560
        ],
        [
          1495230840000,
          3936.6
        ]
      ],
      "key": null,
      "tags": {
        "metric": "xyz",
      },
      "tagCounts": {}
    }```

**Comment by mykolasmith** [comment]
I can confirm that this is only an issue with the "Single" index type.

**Comment by udoprog** [comment]
Hey,

Could you check the mapping for the indexes which return butchered keys?

The following should (I think) do it:

```bash
$> curl curl http://<es>:9200/<index>/_mapping
```

My suspicion is that the index template was not applied correctly for some reason for the particular index you are using.

**Comment by mykolasmith** [comment]
Looks fine to me?

```{
  "heroic": {
    "mappings": {
      "metadata": {
        "properties": {
          "key": {
            "type": "string"
          },
          "tag_keys": {
            "type": "string"
          },
          "tags": {
            "type": "string"
          }
        }
      },
      "tag": {
        "properties": {
          "key": {
            "type": "string"
          },
          "kv": {
            "type": "string"
          },
          "series_id": {
            "type": "string"
          },
          "skey": {
            "type": "string"
          },
          "sval": {
            "type": "string"
          },
          "tag_keys": {
            "type": "string"
          },
          "tags": {
            "type": "string"
          }
        }
      },
      "series": {
        "properties": {
          "key": {
            "type": "string"
          },
          "series_id": {
            "type": "string"
          },
          "tag_keys": {
            "type": "string"
          },
          "tags": {
            "type": "string"
          }
        }
      }
    }
  }
}```

**Comment by udoprog** [comment]
@mykolasmith Thanks for the mapping.

It's actually wrong, this is what it's supposed to look like:

**tag**:
https://github.com/spotify/heroic/blob/master/suggest/elasticsearch/src/main/resources/com.spotify.heroic.suggest.elasticsearch/kv/tag.json

**series**:
https://github.com/spotify/heroic/blob/master/suggest/elasticsearch/src/main/resources/com.spotify.heroic.suggest.elasticsearch/kv/series.json

**metadata**:
https://github.com/spotify/heroic/blob/master/metadata/elasticsearch/src/main/resources/com.spotify.heroic.metadata.elasticsearch/kv/metadata.json

The mentioned mapping would cause the fields to be analyzed (by default) and broken up in the way you described.

**Comment by mykolasmith** [comment]
@udoprog I've deleted that mapping and now trying to PUT the correct mapping (https://gist.github.com/mykolasmith/250a4ca2660c123760449795e20db6c2) and getting the following error: 

`
{
  "error": "MapperParsingException[mapping [series]]; nested: MapperParsingException[Analyzer [prefix_analyzer] not found for field [prefix]]; ",
  "status": 400
}```

Any ideas?

**Comment by udoprog** [comment]
Seems like settings are missing, metadata _and_ suggest is best configured using the `configure` task, as exemplified here:
http://spotify.github.io/heroic/#!/docs/getting_started/configuration#elasticsearch

**Comment by mykolasmith** [comment]
@udoprog Thanks, I did run the `configure` task after switching indexes, so not sure why the index was wrong. I've written it manually to the Elastisearch cluster and everything seems OK now.
