### ISSUE TITLE
Caught SearchContextMissingException and Cluster is very Slow for query

### ISSUE THREAD

**Issue by zhouchaochao** [spotify/heroic#280]
ES version 2.1.2

All data nodes print a large number of SearchContextMissingException logs, like below:
 
```
_[2017-05-21 13:00:28,040][DEBUG][action.search.type       ] [dm_172.18.191.156:30001] [28441965] Failed to execute query phase
RemoteTransportException[[dm_172.18.191.130:30001][172.18.191.130:40101][indices:data/read/search[phase/scan/scroll]]]; nested: SearchContextMissingException[No search context found for id [28441965]];
Caused by: SearchContextMissingException[No search context found for id [28441965]]
	at org.elasticsearch.search.SearchService.findContext(SearchService.java:610)
	at org.elasticsearch.search.SearchService.executeScan(SearchService.java:310)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:433)
	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchScanScrollTransportHandler.messageReceived(SearchServiceTransportAction.java:430)
	at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.doRun(MessageChannelHandler.java:299)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)_
```

now ,My cluster is very slow for query.

ES version 2.1.2
My cluster hava 11 nodes:
    3 nodes with data role, each node has 8G Heap Size
    4 nodes with data and master roles, each node has 8G Heap Size
    4 nodes without role(node.master: false; node.data: false), each node has 6G Heap Size

What happend to my cluster?
I don't know why i have got this logs?
What can i do to fix this?

Thanks for help...

my issue is mostly like https://github.com/spotify/heroic/issues/195

**Comment by udoprog** [comment]
Haven't tried it with 2.1.2, but the following are things to consider from the top of my head:

#### How many time series do you have for the indexes you are hitting?
Usually the number of time series being served is proportional to the size of the cluster. CPU utilization and GC pauses of the cluster is the prime indicator to determine if you need to scale it up.

#### How are the time series being accessed?
Some kinds of queries (e.g. regex queries) are terrible for performance. They would most likely perform the equivalent of a full table scan. Look at your QPs and compare it to your CPU utilization.

#### Indexing overhead
Elasticsearch being a live system is heavily impacted by indexing. You have some potions in Elasticsearch to tweak here, most importantly `index.refresh_interval`. But from Heroic you can tweak the write-through cache. A more aggressive rate limiting means that your time series will take longer to register, but have less of an impact. Again, look at CPU utilization for the cluster to determine this.

#### Keep suggestions separate
Suggestions is a separate backend because it aggressively uses aggregations. These have been notoriously resource hoggy and should be run on a separate cluster. Specifically, indexing suggestions is a factor of 10 more intensive that indexing metadata.

**Comment by zhouchaochao** [comment]
@udoprog 
My index has 16,493,735 docs. i use scroll query. I don't indexing doc to the Index which i do scroll query with. My CPU utilization and load is low.

below is my mapping:

{
  "odp_realtime_ol_self_sku_sum_20170521": {
    "settings": {
      "index": {
        "refresh_interval": "3m",
        "number_of_shards": "8",
        "creation_date": "1495238454198",
        "number_of_replicas": "1",
        "uuid": "q0XLtLsQStapV5jJyhy7HQ",
        "version": {
          "created": "2010299"
        }
      }
    },
    "mappings": {
      "odp_realtime_ol_self_sku_sum": {
        "_ttl": {
          "enabled": false
        },
        "_timestamp": {
          "enabled": true
        },
        "_all": {
          "enabled": false
        },
        "properties": {
          "pv": {
            "index": "no",
            "store": true,
            "type": "long",
            "doc_values": true
          },
          "uvDur": {
            "index": "no",
            "store": true,
            "type": "long",
            "doc_values": true
          },
          "platform": {
            "store": true,
            "type": "integer"
          },
          "categoryName3": {
            "index": "no",
            "store": true,
            "type": "string",
            "doc_values": true
          },
          "visits": {
            "index": "no",
            "store": true,
            "type": "long",
            "doc_values": true
          },
          "categoryName1": {
            "index": "no",
            "store": true,
            "type": "string",
            "doc_values": true
          },
          "itemName": {
            "index": "no",
            "store": true,
            "type": "string",
            "doc_values": true
          },
          "categoryName2": {
            "index": "no",
            "store": true,
            "type": "string",
            "doc_values": true
          },
          "cxDeptId": {
            "store": true,
            "type": "integer"
          },
          "operName": {
            "index": "no",
            "store": true,
            "type": "string",
            "doc_values": true
          },
          "deptId1": {
            "store": true,
            "type": "integer"
          },
          "deptId2": {
            "store": true,
            "type": "integer"
          },
          "deptId3": {
            "store": true,
            "type": "integer"
          },
          "deptId4": {
            "store": true,
            "type": "integer"
          },
          "deptId5": {
            "store": true,
            "type": "integer"
          },
          "brandCode": {
            "index": "not_analyzed",
            "store": true,
            "type": "string"
          },
          "timeRange": {
            "store": true,
            "type": "integer"
          },
          "uv": {
            "index": "no",
            "store": true,
            "type": "long",
            "doc_values": true
          },
          "brandName": {
            "index": "no",
            "store": true,
            "type": "string",
            "doc_values": true
          },
          "categoryId1": {
            "store": true,
            "type": "integer"
          },
          "categoryId2": {
            "store": true,
            "type": "integer"
          },
          "itemId": {
            "store": true,
            "type": "long"
          },
          "categoryId3": {
            "store": true,
            "type": "integer"
          },
          "opTime": {
            "index": "not_analyzed",
            "store": true,
            "type": "string"
          },
          "operErpId": {
            "index": "not_analyzed",
            "store": true,
            "type": "string"
          }
        }
      }
    },
    "aliases": {},
    "warmers": {}
  }
}

**Comment by udoprog** [comment]
@zhouchaochao Hey, that does not look like a Heroic index?

**Comment by zhouchaochao** [comment]
@udoprog 

What does **Heroic index** means ?_?

**Comment by udoprog** [comment]
Heroic is this project, which uses Elasticsearch. 

The mapping you've pasted refers to an index named `odp_realtime_ol_self_sku_sum`, which is not an index that heroic would create or use. How is this related to heroic?

**Comment by zhouchaochao** [comment]
@udoprog 
oh,oh... i am lost!  Thanks for your kindness reply.

**Comment by udoprog** [comment]
Heh, no worries. Best of luck!
