### ISSUE TITLE
heroic.yml working sample

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#294]
hello,

i would like a working sample of heroic.yml conf file corresponding to latest commit
thanks

**Comment by hexedpackets** [comment]
There's a config at [example/heroic.example.yml](https://github.com/spotify/heroic/blob/master/example/heroic.example.yml) that's updated when there are config changes. All the options are documented and commented out there - if you notice something missing definitely let us know or open a PR for it.
