### ISSUE TITLE
Possible issue with compareLists method in FilterUtils.java?

### ISSUE THREAD

**Issue by tariq1890** [spotify/heroic#295]
I found this issue while writing unit tests for the AndFilter and OrFilter classes. 

I  created an AndFilter object named "andFilter" with a couple of other filter objects as statements.

When comparing andFilter with itself ( andFilter.compareTo(andFilter) ), I was asserting a zero value but got a 1 instead.

On debugging I realized it is because of the compareLists method where we are not completely iterating over the list of filter statements.  I guess We need to use a while loop instead of the if loop in line 49. of FilterUtils.java

If this is a valid issue, I can submit a PR with some simple test cases.

Also, If the left is greater than the right in a compare method, shouldn't we return a positive value? I think FilterUtils has it implemented the other way round.

**Comment by udoprog** [comment]
Guessing you mean [this line?](https://github.com/spotify/heroic/blob/96b989b2d749cd97c91ba742e1e40d3b0bc908f5/heroic-component/src/main/java/com/spotify/heroic/filter/FilterUtils.java#L49).

Looks like a bug. Good find!

**Comment by tariq1890** [comment]
Yes! I would like to fix that. 

 I also had this question about the return value 
"Also, If the left is greater than the right in a compare method, shouldn't we return a positive value? I think FilterUtils has it implemented the other way round. " - Am I correct in this assumption ? 

If so, I will make that change as well.
