### ISSUE TITLE
spark

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#299]
Hello,

I want to use spark over cassandra & elasticsearch the same way you use it for heroic.
My first step is to understand how you extract data from elasticsearch and cassandra.
Could you tell me were in the code you translate query from heroic to elasticsearch and to cassandra ?

thanks
Lucile

**Comment by udoprog** [comment]
Any translation happens in the a backend, `MetricBackend` for data, `MetadataBackend` for metadata. Look for child classes of these.

Queries are basically:

* `MetadataBackend`, translate api query to elasticsearch query, run it to get a list of time series.
* `MetricBackend`, for each time series, fetch the specified range and feed into aggregation framework.

The specific implementation depends on the backend. That's where you should look.

**Comment by lucilecoutouly** [comment]
ok 
i use cassandra backend so 
how to query cassandra with series_id from elasticsearch ?
how to use timestamp to query cassandra ? 
what is metric_key ? how to calculate it ?
what is data_time_offset ? how from timestamp you calculate it ?

thank you

**Comment by lucilecoutouly** [comment]
hello . i wandered how you make the key serie ? hash ? 
thank you

**Comment by dmichel1** [comment]
I'm not familiar with the Cassandra side of things but I believe its similar enough to Bigtable.

>how to query cassandra with series_id from elasticsearch ?
how to use timestamp to query cassandra ?
what is metric_key ? how to calculate it ?
what is data_time_offset ? how from timestamp you calculate it ?

With bigtable there is a row key serializer that takes the key + tags of a `series` and then calculates an offset on the timestamp of the actual metric. 

Most of the heavy work is done here - https://github.com/spotify/heroic/blob/master/metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/MetricsRowKeySerializer.java#L123

**Comment by lucilecoutouly** [comment]
thanks for your explanation.
in fact in my cassandra table i have this:

` metric_key                                                                                                                     | data_timestamp_offset | data_value
--------------------------------------------------------------------------------------------------------------------------------+-----------------------+------------
 0x036e72680604636f6f7205302e3132350166043135303904686f7374047273646203696e740131036f72690265770474797065047669737588fafefebe26 |                  2616 |    2.41035
`
so the metric key is:
0x036e72680604636f6f7205302e3132350166043135303904686f7374047273646203696e740131036f72690265770474797065047669737588fafefebe26
and from blob to varchar i have:
nrhcoor0.125f1509hostrsdbint1oriewtypevisu�����&,

it is praticaly understandable 
my tags and key with values are
nrhcoor0.125f1509hostrsdbint1oriewtypevisu

what i don't understand is the end:
88fafefebe26
???
i don't know how to make it ? from the metadata ? hash ?

thanks for replying

**Comment by dmichel1** [comment]
hmm - I'm not sure I understand what is at the end either. What i have found helpful in the past is to use the debugger as part of your IDE (I use Intelij) and set a bunch of break points in classes and methods that involve serializing and deserializing the row key.

Once you actually hit a break point you should get a bunch of variables that are filled out and hopefully one of those variables helps you answer the question of what that is.
