### ISSUE TITLE
no cache

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#309]
Hello,

how to set heroic to desable cache ?
per query ?
all the time ?

thanks

**Comment by udoprog** [comment]
Caching needs to be explicitly enabled through:
* A configuration option `cache`, telling it where to cache.
* A feature flag `com.spotify.heroic.query_cache`, that can be set per-query, or on the API node.

Documentation will be added for it when the feature has stabilized more.

**Comment by hexedpackets** [comment]
This is being documented as part of #440
