### ISSUE TITLE
how to enable and verify aggressive retry policy

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#340]
Hello,

I want to test another retrypolicy and i found you write aggressive one.
 * how to enable aggressive retry policy ?
 *  how to verify aggressive retry policy ?
* what is the best usage ?

Thanks

**Comment by mykolasmith** [comment]
If Spotify abandon this project, it's your fault @lucilecoutouly

**Comment by udoprog** [comment]
Aggressive retry policy should only be used when performing data migrations (e.g. using the `data-migrate` task). It can be quite taxing on the cluster.

Why do you want to use it?

**Comment by lucilecoutouly** [comment]
i want to have my request answered 

i have a cluster of 3 cassandra nodes with replica 3
i would like a retry policy that try 1rst node , a lot of connexion ....etc
when there is no more connexion connect to 2nd node , a lot ....
after 3rd connection on 3rd node ,,,,,

and after retry 1rst node 

in a loop 

how am i doing that ?
