### ISSUE TITLE
Ability to bulk load data?

### ISSUE THREAD

**Issue by jpiper** [spotify/heroic#343]
Is there the ability to bulk load data? At the moment I can only see from the docs that a single request has to be used for each metric, which seems inefficient when these could be bulked into a single request.

i.e the example from the docs:

```json
{
  "series": {"key": "foo", "tags": {"site": "lon", "host": "www.example.com"}},
  "data": {"type": "points", "data": [[1300000000000, 42.0], [1300001000000, 84.0]]}
}
```
if I had the metrics from two sites, one could imagine just allowing an array of these objects, like,

```json
[{
  "series": {"key": "foo", "tags": {"site": "lon", "host": "www.example.com"}},
  "data": {"type": "points", "data": [[1300000000000, 42.0], [1300001000000, 84.0]]}
},
{
  "series": {"key": "foo", "tags": {"site": "nyc", "host": "www.example2.com"}},
  "data": {"type": "points", "data": [[1300000000000, 50.1], [1300001000000, 99.5]]}
}]
```

**Comment by udoprog** [comment]
Hey,

The HTTP APIs are generally not suitable for loading large amounts of data. While you can load multiple samples for a single time series, we should try to keep it small. Each write also stores metadata in Elasticsearch, which is a potentially expensive process.

The recommended approach would be to make use of a shell task, unfortunately no task exists to load data from disk. The closest we have today is data-migrate, which loads from one metric backend to another:
https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/shell/task/DataMigrate.java

We could also build a metric backend which reads the data from some location on disk. This would permit using the existing data-migrate task.
The following is an example of the simplest metric backend we have today which is primarily used for testing. It stores everything in-memory:
https://github.com/spotify/heroic/tree/master/metric/memory/src/main/java/com/spotify/heroic/metric/memory

I've marked this as an Enhancement so someone can take a stab at it if they want to.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
