### ISSUE TITLE
Only create a Cassandra keyspace if it doesn't exist when CREATE permission is missing

### ISSUE THREAD

**Issue by udoprog** [spotify/heroic#35]
The current approach `CREATE KEYSPACE IF NOT EXISTS` apparently doesn't work without `create` permissions.
1. Consider if there's another way to detect if a keyspace exists before attempting to create it.
2. Allow for explicitly disabling the creation of a keyspace so it's not attempted.

This relates to #34

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
