### ISSUE TITLE
 Response received on stream 4480 but no handler set anymore

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#350]
hello 

on big request s get this trace 
```
2017-12-21 11:59:08,055 DEBUG c.d.d.c.Connection [cluster1-nio-worker-4] Connection[cassandraseedprod/172.19.0.10:9042-2, inFlight=265, closed=false] Response received on stream 4480 but no handler set anymore (either the request has timed out or it was closed due to another error). Received message is ROWS [2 columns] (to be continued)
 | 0x76cea20f | 0xbfcda9da597d49d8
 | 0x76cea5f7 | 0xbfcda9da597d49d8
 | 0x76cea9df | 0x3fc5af640639d5e5
 | 0x76ceadc7 | 0xbfcda9da597d49d8
 | 0x76ceb1af | 0xbfcda9da597d49d8
 | 0x76ceb597 | 0xbfcda9da597d49d8
 | 0x76ceb97f | 0xbfcda9da597d49d8
 | 0x76cebd67 | 0x3fb0881ff4920db4
 | 0x76cec14f | 0xbfcda9da597d49d8
 | 0x76cec537 | 0x3fc483fd50225743
 | 0x76cec91f | 0xbfb2c1c029505b62
 | 0x76cecd07 | 0xbfcda9da597d49d8
 | 0x76ced0ef | 0xbfcda9da597d49d8
 | 0x76ced... [message of size 175038 truncated] 
```

and the request fall down 
any idea ?

thanks

**Comment by lucilecoutouly** [comment]
someone say : 

> With regards to this log message, it typically either means that your query timed out or was cancelled (either by calling Future.cancel() or speculative execution canceling it) and the response was received by the driver after this fact, so this is just a DEBUG message letting you know that the response was eventually received but there's nothing to do with it because the driver has already taken action on the user's request.

were may i found the Future.cancel()  in the source code of HEROIC ?

**Comment by udoprog** [comment]
We generally only call cancel if the client hangs up before receiving a response from the server or times out (after 600 seconds), here:
https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/common/CoreJavaxRestFramework.java#L87

**Comment by lucilecoutouly** [comment]
where do you write times out = 600 seconds ?

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
