### ISSUE TITLE
Bigtable row key design

### ISSUE THREAD

**Issue by garye** [spotify/heroic#364]
Hi,

I'm interested in understanding how you're using Bigtable, in particular how you've designed your row key and schema. 

From a quick glance at the code you seem to be using a slightly different format than OpenTSDB (http://opentsdb.net/docs/build/html/user_guide/backends/hbase.html) - it looks like the timestamp is the final part of the key. 

Any details or insights about how this is working for you would be appreciated!

**Comment by nezdolik** [comment]
Hi @garye,

Our system is write-heavy, row key has the following structure: [key,{key-value pairs},base value]. 
Key is a string value that defines granular namespace for set of key-value pairs.
Base value is used for partitioning over time, we use 4 billion-sized partitions. 
Take a closer look how it is defined here: https://github.com/spotify/heroic/blob/master/metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/BigtableBackend.java#L455
We have 2 types of column families: metrics and events. Within each column family we have no more than 4 billion cells (which if fine as cells can be sparse).
Structure of row key is defined here: https://github.com/spotify/heroic/blob/master/metric/bigtable/src/main/java/com/spotify/heroic/metric/bigtable/RowKey.java
You could also read up on general guidelines here https://cloud.google.com/bigtable/docs/schema-design-time-series

**Comment by garye** [comment]
Thanks!

**Comment by uschen** [comment]
@nezdolik 
I wonder if you can shed some light on if `[key,{key-value pairs},base value].` row key design helps filtering the `key-value` pairs.

**Comment by dmichel1** [comment]
@uschen when you make a query against heroic - it first looks up all possible keys matching a filter in its metadata which is currently backed by elasticsearch. Once it fetches all the keys it serializes it into a `rowkey` which is then looked up in Bigtable.

We don't perform any scans across Bigtable for performance reasons.

**Comment by uschen** [comment]
@dmichel1 in that case, wouldn't be better to build the metadata indexes in bigtable too? since it seems Elasticsearch is over kill for `looks up all possible keys matching a filter`? I wonder if you can shed some light on using elasticsearch.

**Comment by dmichel1** [comment]
@uschen the below references are really good reads into bigtable.

https://cloud.google.com/bigtable/docs/schema-design
https://cloud.google.com/bigtable/docs/schema-design-time-series

Essentially Bigtable is a giant K/V store with only 1 index, the row key that is lexicographically sorted. When performing a query for a given time series, if we did not know what the `Series`was we would have to perform a table scan against almost a petabyte of data.

**Comment by uschen** [comment]
@dmichel1 sorry for not asking the question clearly.

I meant to say it seems to be possible to build secondary indexes (in other tables) in bigtable to allow filtering matched keys by labels, resources, instead of replicating part of the data to elasticsearch for indexing.

**Comment by dmichel1** [comment]
No worries, and I understand what you are saying now, thanks.

I would love to move away from ES and that is definitely an interesting idea. 

For replacing the metadata ES cluster it would need to do the same logic that starts here to find series, https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/metric/LocalMetricManager.java#L340

The suggest ES cluster I think will be too difficult to not have "true" search functionality.

You can read more about what the different ES clusters do here
https://spotify.github.io/heroic/docs/config/metadata
