### ISSUE TITLE
delete data from series between date range

### ISSUE THREAD

**Issue by lucilecoutouly** [spotify/heroic#368]
hello,

is it possible to delete some data in cassandra for range timestamp 
but without deleting the whole serie ?

**Comment by udoprog** [comment]
No cush interface right now I'm afraid. Generally we'd recommend that you configure Cassandra to automatically delete data after a period of time using some time-based compaction.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
