### ISSUE TITLE
No way to configure cassandra schema and table in docs

### ISSUE THREAD

**Issue by dimaslv** [spotify/heroic#39]
The only configuration step for cassandra according to docs is running tools/heroic-shell -P cassandra -X cassandra.seeds=<seeds> -X cassandra.configure, but it fails with "Keyspace heroic does not exist".
It works only after importing keyspace.cql and tables.cql manually.

**Comment by udoprog** [comment]
Potential bug in the autoconfiguration code, will investigate.

**Comment by jcabmora** [comment]
Confirm I had the same problem.

**Comment by udoprog** [comment]
This seems to have been a documentation mistake. The name of the switch is `-X datastax.configure`, or alternatively just `-X configure`.

This has been fixed in the documentation for getting started.

**Comment by jcabmora** [comment]
Confirm that 9aa9e28 fixed the problem!  Thanks so much, @udoprog!
