### ISSUE TITLE
Document aggregations of resource identifiers

### ISSUE THREAD

**Issue by hexedpackets** [spotify/heroic#451]
When talking various squads the use case for this is as follows. Alerts are typically a max/avg within a given region. When an alert fires the on-call person will often change the aggregation from region -> instance.

With kubernetes, instance is now becoming podname which is not in the suggest index. With  Grafana, it should be documented that resource identifiers can be added free-form even though they won't show up as suggestions. 

Also for a nicer UX perhaps we can have a fixed list of RI's or get the list of RI's returned by the query to populate the dropdown.

**Comment by lmuhlha** [comment]
Moved the feature request UX part to https://github.com/spotify/heroic/issues/560

**Comment by lmuhlha** [comment]
https://github.com/spotify/heroic/pull/561
