### ISSUE TITLE
Fix tracing memory leak (Heroic-api) 

### ISSUE THREAD

**Issue by lmuhlha** [spotify/heroic#469]
Memory leak caused slow heroic request responses

Currently the thought is that a memory leak in the tracing library was causing this, only triggered by an increased number of metrics/tags

**Comment by lmuhlha** [comment]
- Running heroic with new JVM args and enabled tracing again 
- Noticed the used memory on the gae node double in the time I had tracing enabled 
- Logs don't look too out of the ordinary

**Comment by lmuhlha** [comment]
- Left this running on 2 machines to see if the issue could be replicated, but it didn't come up
- Might be a grpc issue and require more machines across regions running tracing to replicate this
- Going to wait on upstream issue resolutions to pick this back up again: 
Memory Settings - https://github.com/census-instrumentation/opencensus-java/issues/1767
Decide what to do when async event queue is full - https://github.com/census-instrumentation/opencensus-specs/issues/262
Configure a max number spans in RunningSpanStoreImpl - https://github.com/census-instrumentation/opencensus-java/issues/1813

**Comment by dmichel1** [comment]
Fixed in https://github.com/census-instrumentation/opencensus-java/releases/tag/v0.22.0
