### ISSUE TITLE
Support for predict_linear for SLO burn rate

### ISSUE THREAD

**Issue by lmuhlha** [spotify/heroic#475]
predict_linear()
predict_linear(v range-vector, t scalar) predicts the value of time series t seconds from now, based on the range vector v, using simple linear regression.

predict_linear should only be used with gauges.

**Comment by hexedpackets** [comment]
@dmichel1 I think it makes sense to close out this issue. Its very vague, and we don't have any plans to implement this. It isn't clear to me if its even something worth implementing as the use case of predictint SLO burn is very specific to bundle into Heroic.

If you feel strongly about this, I think we should start an RFC to think through what this would look like like.

**Comment by dmichel1** [comment]
Fine with closing it given we have #481 open. If we decide support prometheus remote reads we can get this functionality that way.
