### ISSUE TITLE
Problems with query/metrics API

### ISSUE THREAD

**Issue by jcabmora** [spotify/heroic#48]
We have been testing the `query/metrics` API and we had some confusing results.  The biggest problem that we have found is that the end of ranges changes based on the length of the range.  We believe this inconsistency can potentially affect usability, ease of consumption of the APIs by frontends and why not, unit testing.

Here's the procedure that we have followed to put this in evidence:

1) make a call to the `query/metrics` API with a relative range of 1 second and extract the latest time in milliseconds.  We are aware this is an approximation and the response latency between this call and the next call make it inaccurate.  At this point we just want to get a lower bound of the heroic server date since we are going to be using calls with "relative" ranges.

2) immediately make a call to the `/write` API to push two data points, one with the time obtained in the previous step and another data point one second earlier

3) make several calls to the `query/metrics` API using an absolute range of +_ 1500 milliseconds, and relative ranges of 5 seconds, 1 day and 3 days.  We have noticed in the responses to these calls:

- for the absolute range, the returned range in the response does not correspond to the requested range
- the 5 second range includes the two added datapoints, and the start and end are usually within reasonable values (considering the latencies of the requests/responses)
- the 5 minutes range is shifted, usually to a timestamp that is before in time than the end of the previous response. Sometimes the rows added in step 2 are returned, sometimes they are not.
- the 3 day range is shifted even more, making the recently added rows to not be returned.

We believe the reason for this is the logic that is implemented in the [buildShiftedRange()](https://github.com/spotify/heroic/blob/master/heroic-core/src/main/java/com/spotify/heroic/CoreQueryManager.java#L299-L315) method.   I do believe that logic might apply in many situations, a perfect example could be when you want to aggregate data on time slots, and data will only make sense if all slots are of the same size, but when you do not need to aggregate data based on time and just want to return data points, or your aggregation is, say for example, based on device type, then the logic of shifting ranges does cause unexpected results to be returned.  To test this, we used [this bash script](https://gist.github.com/jcabmora/d7bbab37f82290f67b8b9501e6fa40d2) (you'll need `jq` installed on your machine to be able to test this.  Also, all calls are made to localhost:8080 , so you might need to update accordingly)

**Comment by juruen** [comment]
Hi,

The current behavior is expected. We basically do two things: we round up intervals to the closet aggregation bucket, and we also shift the range slightly if it's too close to _now_ to allow some time for the metrics to arrive. This means that your queries might look different depending on timing. We do this because it fits better our use of Heroic.

Having said that, we acknowledge that this may be confusing and not what you would expect to happen. We have discussed it internally, and we believe it would make sense to add a feature flag that could be added to the configuration or the query to enable this behavior. This way, we could use a default behavior that is more intuitive for the user.

Thanks!

**Comment by jcabmora** [comment]
HI @juruen.

Thank you for the response.  We completely understand.  We'll be interested in contributing on this enhancement.  What would be the best way for us to proceed?

Jorge
