### ISSUE TITLE
Support Elasticsearch 2.x

### ISSUE THREAD

**Issue by udoprog** [spotify/heroic#50]
Bump the Elasticsearch version and test to support `2.x`.

This will not be a backwards compatible change because of [elastic/elasticsearch#13272](https://github.com/elastic/elasticsearch/issues/13273) unless we switch to some REST client.

**Comment by dbrounst** [comment]
We at, Ciena, have made the changes for Elasticsearch 2.2.1.  Please review, accept, etc.. the changes here: https://github.com/spotify/heroic/pull/62

Thanks to:
Bo Wen bwen@ciena.com
Jorge Cabrer jocabrer@ciena.com
Dave Brounstein dbrounst@ciena.com

**Comment by dbrounst** [comment]
Please contact me regarding updating the docs.  There needs to be changes to reflect:
- Elasticsearch 1.7.1 -> Elasticsearch 2.2.1 
- Elasticsearch 2.2.1 install-elasticsearch-tarball.sh must add the plugin: /opt/elasticsearch/bin/plugin install delete-by-query

**Comment by valentinul** [comment]
No updates on this ? 
ES 2.x would be a great improvement... 
I have to run a separate ES cluster just for heroic because of the 1.7 branch compatibility....

**Comment by dbrounst** [comment]
I don't have time to make the changes requested in the change request. It is in a state that works for us using 2.2.1 
Here is the PR: https://github.com/spotify/heroic/pull/62
Here is my fork: https://github.com/dbrounst/heroic
Feel free to continue my work.

**Comment by valentinul** [comment]
Thanks for the reply.
I'm going to checkout your fork and try to bring it up to latest and see how it behaves. 

Thanks for the work!

**Comment by dmichel1** [comment]
Closing -- ES2 support has long been dropped.

https://github.com/spotify/heroic/pull/267 & https://github.com/spotify/heroic/pull/366
