### ISSUE TITLE
[tracing] Link spans properly

### ISSUE THREAD

**Issue by lmuhlha** [spotify/heroic#505]
the http -> grpc spans are not linked. 
the grpc -> grpc spans are not linked (cross region spans)
the http -> grpc -> bigtable spans are not linked correctly.

Any leanings on how to pass context between highly async requests should be documented for others.

**Comment by dmichel1** [comment]
After #615 the only think left is to link the http call to `CoreQueryManager`

**Comment by dmichel1** [comment]
This has been completed as of #621
