### ISSUE TITLE
A kafka corrupt message makes the consumer get stuck

### ISSUE THREAD

**Issue by juruen** [spotify/heroic#53]
One of our consumers stopped consuming. While looking into the log we found the exception below. A restart didn't help, as soon as the faulty message was read the consumer would stop.

My initial research seemed to indicate that you can't recover from this programmatically. However, we should verify this is the case and that is not already addressed in a newer version.

I had to resort to remove the partition that contained the faulty message as we could afford doing so. Although maybe increasing the offset in ZK is enough if this happens again before it is properly fixed.

>  2016-06-17 09:36:47,193 ERROR c.s.h.c.k.ConsumerThread [com.spotify.heroic.consumer.kafka.ConsumerThread:]:0: Error in thread kafka.message.InvalidMessageException: Message is corrupt (stored crc = 0, computed crc = 225171
> 0752)
> at kafka.message.Message.ensureValid(Message.scala:166)
> at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:102)
> at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
> at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
> at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
> at com.spotify.heroic.consumer.kafka.ConsumerThread.guardedRun(ConsumerThread.java:140)
> at com.spotify.heroic.consumer.kafka.ConsumerThread.run(ConsumerThread.java:89)

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
