### ISSUE TITLE
POST: /query/metrics does not seem to work

### ISSUE THREAD

**Issue by dakoos** [spotify/heroic#54]
I build heroic-db (commit 54f44433ccebe1585db21790fe717f7abce0fd96) and the service is up and running using Cassandra as the back end (but no Elastic Search). The service is up and running where both GET /status and POST: /write do not return back errors.

However, the following two queries are returning back errors:
curl -H "Content-Type: application/json" http://localhost:8080/query/metrics \
  -d '{"range": {"type": "relative"}, "filter": ["and", ["key", "foo"], ["=", "foo", "bar"], ["+", "role"]], "groupBy": ["site"], "aggregation": []}'
This example is from https://spotify.github.io/heroic/#!/docs/api and the error message is the following:
 {"message":"Unexpected token (END_ARRAY), expected VALUE_STRING: need JSON String that contains type id (for subtype of com.spotify.heroic.aggregation.Aggregation)","reason":"Bad Request","status":400,"path":"aggregation","type":"json-error"}

I tried changing the query instead to the following:
curl -X -H "Content-Type: application/json" http://localhost:8080/query/metrics \
  -d '{"range": {"type": "relative", "string": "MONTHS", }, "filter": ["and", ["key", "foo"], ["=", "foo", "bar"], ["+", "role"]], "groupBy": ["site"], "aggregation": []}'

And I am now getting this error message:
curl: (6) Could not resolve host: Content-Type; Unknown error
{"message":"HTTP 405 Method Not Allowed","reason":"Method Not Allowed","status":405,"type":"error"}

I am looking at the logs and I am not seeing anything there which indicates why the queries are failing.

**Comment by udoprog** [comment]
Hey,

The command you paster is malformed. `-X` expects the method as a parameter, like `-X POST`. In fact, it can be omitted because it's implied with `-d`.

**Comment by dakoos** [comment]
I tried the following:
curl -X POST -H "Content-Type: application/json" http://localhost:8080/query/metrics \
-d '{"range": {"type": "relative", "string": "MONTHS", }, "filter": ["and", ["key", "foo"], ["=", "foo", "bar"], ["+", "role"]], "groupBy": ["site"], "aggregation": []}'

Now the error message is:

{"message":"Unexpected character ('}' (code 125)): was expecting double-quote to start field name\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@5fd19f15; line: 1, column: 53]","reason":"Bad Request","status":400,"path":"range","type":"son-error"}

The JSON looks to be valid. Also, the first request is having the same error even I specify '-X POST'.

**Comment by dakoos** [comment]
Actually, the curl request I sent above was slightly malformed:

curl -X POST -H "Content-Type: application/json" http://localhost:8080/query/metrics \
-d '{"range": {"type": "relative", "string": "MONTHS" }, "filter": ["and", ["key", "foo"], ["=", "foo", "bar"], ["+", "role"]], "groupBy": ["site"], "aggregation": []}'

Now, there are no longer any JSON errors. But I am still receiving a Heroic error:
{"message":"Unrecognized field \"string\" (class com.spotify.heroic.QueryDateRange$Relative), not marked as ignorable","reason":"Bad Request","status":400,"path":"range.string","type":"json-error"}

**Comment by dakoos** [comment]
Also, I have been trying to play with the query and I have created:

curl -H "Content-Type: application/json" http://localhost:8080/write \
>   -d '{"series": {"key": "foo", "tags": {"site": "lon", "host": "www.example.com"}}, "data": {"type": "points", "data": [[1466560275000, 42.0]]}}'
{"errors":[],"times":[9555074]}

curl -H "Content-Type: application/json" http://localhost:8080/query/metrics   -d '{"range": {"type": "relative", "unit": "DAYS", "value":100}, "filter": ["key", "foo"], "groupBy": ["site"], "aggregators": []}'
{"range":{"start":1457922165961,"end":1466562165961},"trace":{"what":{"name":"com.spotify.heroic.CoreQueryManager#query"},"elapsed":75,"children":[{"what":{"name":"com.spotify.heroic.cluster.LocalClusterNode#query"},"elapsed":6,"children":[{"what":{"name":"com.spotify.heroic.metric.LocalMetricManager#query"},"elapsed":79,"children":[]}]}]},"limits":[],"commonTags":{},"result":[],"errors":[]}

In such a situation, the newly inserted record should fall within the query. However, results is being set to empty.

**Comment by dakoos** [comment]
I was able to resolve the issue by installing ElasticSearch 1.7 (not 2.x which should also be mentioned in the docs) for the above query. However, could you explain what went wrong with the initial set of queries. 

Also, the documentation is outdated as far as the API goes in https://spotify.github.io/heroic/#!/docs/api.

For example:
curl -H "Content-Type: application/json" http://localhost:8080/write \
>   -d '{"series": {"key": "foo", "tags": {"site": "lon", "host": "www.example.com"}}, "data": {"type": "points", "data": [[1466560275000, 42.0]]}}'
{"errors":[],"times":[15603449,1383935,1389086,1393517,1408274]}

The API doc mentions that the response of "ok": true should be returned back but we are getting back two fields back.

**Comment by udoprog** [comment]
I've updated some of the comments to make them easier to read.

Supported Elasticsearch versions are mentioned in the README, `2.0` support is tracked by #50.

I'll add a task to look over the API documentation more closely.

**Comment by hexedpackets** [comment]
Closing due to age, feel free to re-open if this is still an issue.
