### ISSUE TITLE
Log spam from io.grpc.internal.TransportSet$TransportListener to console

### ISSUE THREAD

**Issue by dakoos** [spotify/heroic#56]
Start heroic via java -cp heroic.jar -Dlog4j.configurationFile=config/log4j2-file.xml com.spotify.heroic.HeroicService heroic.yaml.

Then, on the console, we get a constant stream of the following messages:

> Jun 22, 2016 7:29:05 PM io.grpc.internal.TransportSet$TransportListener transportTerminated
INFO: Transport io.grpc.netty.NettyClientTransport@d6179e1(localhost/127.0.0.1:0) for localhost/127.0.0.1:0 is terminated
Jun 22, 2016 7:30:05 PM io.grpc.internal.TransportSet$1 call
INFO: Created transport io.grpc.netty.NettyClientTransport@5405e612(localhost/127.0.0.1:0) for localhost/127.0.0.1:0
Jun 22, 2016 7:30:05 PM io.grpc.internal.TransportSet$TransportListener transportShutdown
INFO: Transport io.grpc.netty.NettyClientTransport@5405e612(localhost/127.0.0.1:0) for localhost/127.0.0.1:0 is being shutdown
Jun 22, 2016 7:30:05 PM io.grpc.internal.TransportSet$TransportListener transportTerminated
INFO: Transport io.grpc.netty.NettyClientTransport@5405e612(localhost/127.0.0.1:0) for localhost/127.0.0.1:0 is terminated

Even, setting io.grpc to ERROR in the log4j2.xml file does not fix this issue.

**Comment by udoprog** [comment]
Hey,

It would appear that `java.util.logging` is currently not covered by our SLF4J configuration.

I've started working on the `logging` branch to try to address this, you can take a shot yourself with this if you want to.

The easiest way to exercise this code is to fire up HeroicShell like this:

```
tools/heroic-shell -debug -P cluster -X cluster.host=grpc://localhost -X cluster.protocol=grpc
```

This will cause it to listen for remote debug connections on 5005, you can then connect with a debugger using an IDE.
To cause the log statement to be run, you can issue a `refresh` command.

```
heroic> refresh
Jun 23, 2016 5:15:13 PM io.grpc.internal.TransportSet$1 call
INFO: Created transport io.grpc.netty.NettyClientTransport@41f35f7c(localhost/127.0.0.1:0) for localhost/127.0.0.1:0
Jun 23, 2016 5:15:13 PM io.grpc.internal.TransportSet$TransportListener transportShutdown
INFO: Transport io.grpc.netty.NettyClientTransport@41f35f7c(localhost/127.0.0.1:0) for localhost/127.0.0.1:0 is being shutdown
Jun 23, 2016 5:15:13 PM io.grpc.internal.TransportSet$TransportListener transportTerminated
INFO: Transport io.grpc.netty.NettyClientTransport@41f35f7c(localhost/127.0.0.1:0) for localhost/127.0.0.1:0 is terminated
```

I'll continue working on this when I get a bit of time.

**Comment by udoprog** [comment]
This should now work in master. Please verify.
