### ISSUE TITLE
Cadence: 0 when using Whatever-K

### ISSUE THREAD

**Issue by nikek** [spotify/heroic#58]
Seems like any time series value for `cadence` gets lost after being passed through any of the K filters. Is there a reason for this or could we just pass on the cadence that each time series get from the sample aggregation prior to the K filter (if there is one)?

**Comment by udoprog** [comment]
I believe this has been fixed in master, but needs verification and a test case.

**Comment by udoprog** [comment]
This has now been fixed and verified with #86.
