### ISSUE TITLE
Chain aggregation broken in Heroic 0.10.x

### ISSUE THREAD

**Issue by hampusohlsson** [spotify/heroic#580]
After updating Heroic to 0.10.2 some of our queries stopped working. After investigating, it looks like it's related to queries using the `chain` aggregation type.

Consider this query that used to work...

```
{
  ...
  "aggregation": {
    "type": "chain",
    "chain": [
      { "type": "delta" },
      { "type": "sum", "size": "60s" }
    ]
  }
}
```

...now returns a 400 Bad Request with the following error:
> Cannot construct instance of `com.spotify.heroic.aggregation.Chain` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

I see the docs were [removed](https://github.com/spotify/heroic/commit/814c31d4a2cbf4fd6d7f21cb1f39b7e5dab4d2de#diff-9998fb4e34faea7701eaffa4c4a29cdaL22) on Oct 3, 2019.  However, the API still lists `chain` as a valid aggregation type (which are returned when passing an invalid aggregation type)

> Could not resolve type id 'foo' as a subtype of [simple type, class
com.spotify.heroic.aggregation.Aggregation]: known type ids = [
abovek, average, belowk, bottomk, cardinality, **chain**, collapse, count, 
delta, deltaPerSecond, empty, group, group-unique, max, min, notNegative, 
opts, pointsabove, pointsbelow, quantile, spread, stddev, sum, sum2, topk, tpl]

Has the `chain` aggregation type been deprecated?  Or did the query syntax change somehow?

**Comment by lmuhlha** [comment]
Hey @hampusohlsson 
Thanks for bringing this up! We are going to look into what broke chain aggregations and either fix or deprecate it as a result. It likely broke as a result of removing lombok recently. 
Will update you as soon as we have more information!

**Comment by hampusohlsson** [comment]
@lmuhlha thanks for the quick reply! I'm not familiar enough with Java to tell why it stopped working, but Google indeed suggests it has something to do with lombok, or jackson + parameter naming.

As a side note, I actually did some source code digging and found out the chain aggs work if you use the legacy `"aggregators": [ <agg>, ... ]` syntax. 

And please, do not deprecate the chain aggregation :) we use it in production and need to upgrade to 0.10.3 since it contains some important bug fixes.

**Comment by lmuhlha** [comment]
Just an update before the weekend hits:

Looks like we won't be deprecating this functionality. I have a PR in progress with the fix, just need to finish up the tests:
https://github.com/spotify/heroic/pull/581

Thanks again for pointing this out :)

**Comment by jakepeyser** [comment]
Hi @lmuhlha, is there any update on the fix?

**Comment by lmuhlha** [comment]
Hey @jakepeyser ,
I’ve been away at kubecon this week but I will be back on it Monday. 

Thanks for your patience!

**Comment by jakepeyser** [comment]
Thank you for merging the fix @lmuhlha! Do you expect it to be included in a new release in the near future?

**Comment by lmuhlha** [comment]
New release has the fix :)
https://github.com/spotify/heroic/releases/tag/0.10.4
