### ISSUE TITLE
Version for Heroic is not set in Docker build

### ISSUE THREAD

**Issue by hexedpackets** [spotify/heroic#583]
The version is detected on build based on an environmental variable. That variable is set by the CI system, but when its lost when running in the Docker Hub.

Some options I can think of, in no particular order:

- figure out if the docker hub has a similar environmental variable we can use - might not work for building `latest`
- publish the JAR from travis and have the docker build use that instead of building from source
- set the version in source instead of detecting the env var

**Comment by sjoeboo** [comment]
Should be able to get that via: https://docs.docker.com/docker-hub/builds/advanced/#environment-variables-for-building-and-testing
