### ISSUE TITLE
Deprecate group by field

### ISSUE THREAD

**Issue by dmichel1** [spotify/heroic#600]
`POST: /query/metrics` can accept a groupBy field that has been deprecated by "grouping aggregations".

`groupBy` should be removed from the API.

**Comment by lmuhlha** [comment]
Made a PR for this specifically: https://github.com/spotify/heroic/pull/602

But if we're gonna go ahead and do some cleanup, should we just cleanup that whole legacyCreate() set up instead of removing parts?
