### ISSUE TITLE
Decide on versioning semantics

### ISSUE THREAD

**Issue by hexedpackets** [spotify/heroic#606]
We started discussing internally but didn't come to a consensus on how we want to version things now that we're in a post-1.0-society. Some options, definitely open to others:

- [Semantic versioning](https://semver.org/): any breaking changes (eg PR #602) would trigger a new major release, new features is a minor version, bug fixes are patch version
- Snapshotted rolling releases: just cut a release every day/week/month/whatever. Doesn't play nicely with Java build tooling but I don't think that matters for Heroic
- Semantic-ish versioning: major release at our discretion, minor for large changes/backwards incompatible change, patch for small bugs/small features

One nicety about going with semantic versioning is users can have confidence that a minor update won't break their system.

@spotify/observability thoughts?

**Comment by dmichel1** [comment]
I would vote for `Semantic versioning` + clearly marked experimental features that can change at any time.

The experimental bit is similar to how prometheus calls this out https://prometheus.io/docs/prometheus/latest/stability/

Before publishing `2.0.0` we should go through all the code + github issues and make sure anything we want changed is changed so we aren't releasing major versions every other week (e.g. https://github.com/spotify/heroic/issues/496).

**Comment by lmuhlha** [comment]
Yeah I think this just comes down to better planning / release cadence. But i'd like to use semantic versioning as well.

**Comment by hexedpackets** [comment]
I'm a bit iffy on using semver. I think the rigidity is a disadvantage. Not every breaking change is equal, some are legitimately disruptive and warrant a big announcement, but others are tiny and affect few to no users. With semver, both types require a major version bump.

That said, if we do go with semver then +1 to what @dmichel1 said - we should bundle breaking changes together. Maybe handle branching a bit differently in case we need to to release intermediate bugfixes without breaking any APIs.

**Comment by lmuhlha** [comment]
I mean we could go semantic-ish but that mostly just feels like cheating :P 
I don't personally like the rolling releases option.

**Comment by malish8632** [comment]
+1 for semver with bundling of breaking changes

**Comment by hexedpackets** [comment]
Sounds like semver is the winning choice. I'll make a 2.0 milestone so we can tag any breaking changes we want to bundle up with that before cutting it. If we need to release before then, we'll have to keep cherry-picking so we don't pull in the groupBy removal.
