### ISSUE TITLE
Support additional ES index settings

### ISSUE THREAD

**Issue by hexedpackets** [spotify/heroic#622]
When elasticsearch (either metadata or suggest) is enabled with `configure: true`, Heroic will write the expected mappings to as an index template. Ideally, using the built-in `configure` should provide all the configuration needed for a dedicated ES cluster. At a minimum this means adding replica/shard settings to the template.

**Comment by sjoeboo** [comment]
should piggy back on this for delayed shard allocation as well, providing reasonable defaults in the template is 👍
