### ISSUE TITLE
document how to use metric quotas and limits field

### ISSUE THREAD

**Issue by dmichel1** [spotify/heroic#630]
it's not intuitive on how the settings in the [metrics config](https://spotify.github.io/heroic/docs/config#metrics_config) can be used to enforce quotas to protect heroic from large queries.

[post-query-metrics](https://spotify.github.io/heroic/docs/api/post-query-metrics) is also missing the `limits` field, the possible values and what they mean.

related to https://github.com/spotify/spotify-heroic-datasource/issues/131 and https://github.com/spotify/heroic/issues/433

**Comment by sjoeboo** [comment]
fixed in #666
