### ISSUE TITLE
Implement basic rate limiting for query API

### ISSUE THREAD

**Issue by malish8632** [spotify/heroic#675]
Add ability to configure HTTP API to rate limit any [endpoints](https://spotify.github.io/heroic/docs/api)

Currently an API will slow down and start affecting other users.

**Comment by sming** [comment]
FTR we (@smstone and @sming) are compiling an analysis document which will be pasted here once our findings have been finalized.

**Comment by sming** [comment]
Hey @smstone , I know you're down to do this one but could I take it off your plate? It looks like you've been hammered with ffwd and on call? Cheers.

**Comment by sming** [comment]
just a note that I'm resuming work on this from Steven.

**Comment by sming** [comment]
[Here](https://docs.google.com/document/d/1IMUx01vmIUvGi2yXwOPIMe-DsAyfGee2A5hdRiOXaGE/edit#heading=h.uga21h7hk24x) is the doc for this work.

**Comment by sming** [comment]
Closing - moved to [PRISM-2192](https://jira.spotify.net/browse/PRISM-2192) since this work will be done in Envoy.
