### ISSUE TITLE
Issue with Expression parsing

### ISSUE THREAD

**Issue by jcabmora** [spotify/heroic#76]
Hi guys,

I am using the `metadata-fetch` task from HeroicShell.  I ran into some inconsistencies in how the filters are parsed that I believe are caused by how the HeroicQuery grammar is defined.  
As an example, supposed these two keys exist: `4cf41d4b-a5d2-420e-b008-644f0b3d7832` and `c89bf1ee-32ad-44c9-9641-5ee7fe3cac17`. If I run this command I can successfully get the series related to key `c89bf1ee-32ad-44c9-9641-5ee7fe3cac17`:
`metadata-fetch $key = c89bf1ee-32ad-44c9-9641-5ee7fe3cac17`
However, if I run the same for the other key, I get a `com.spotify.heroic.grammar.ParseException`:
`metadata-fetch $key = 4cf41d4b-a5d2-420e-b008-644f0b3d7832`
I found that you have to escape the whole expression to be able to make it work:
`metadata-fetch '$key = "4cf41d4b-a5d2-420e-b008-644f0b3d7832"'`

This problem only happens with expressions that begin with a numeric.  I believe the problem is caused  when [this Rule](https://github.com/spotify/heroic/blob/master/heroic-parser/src/main/antlr4/com/spotify/heroic/grammar/HeroicQuery.g4#L55) is applied, `expr` is matched first for an `ExpressionInteger` and then instead of finding `EOF` if finds the rest of the string.  When quotes are applied it correctly matches `QuotedString`.  I know this can be worked around, but probably having consistency in the syntax would be good.

Regards,

Jorge

**Comment by udoprog** [comment]
This issue happens because `SimpleString` requires a non-digit as the first character. For `4cf41d4b-a5d2-420e-b008-644f0b3d7832` lexer will output `Integer { "4" } SimpleString { "cf41d4b-a5d2-420e-b008-644f0b3d7832" }' which matches none of the parser rules.

I've marked this as an enhancement since it was intentional. I've addressed this in a soon to come pull request.

**Comment by jcabmora** [comment]
Thanks!!
