### ISSUE TITLE
Downloads often cancel (stall) and no auto-resuming happens.

### ISSUE THREAD

**Issue by jarrard** [spotify/heroic#765]
With the latest Heroic application via the Arch AUR, and all previous, downloads of games via the APP with often cancel (stall) and never resume until manual intervention. 

I do not know if this is the API end issue or the GUI app heroic doing this, but its possible the download servers are unstable to Australian users and simply can't resume by themselves. 

I would suggest adding a option to attempt auto-resume of games that cancel/stall during installation.

**Comment by jarrard** [comment]
Additionally the application stalls somewhat at this point and doesn't allow proper cancellation of downloads, it asks to keep installing, yes or no... these do nothing.

**Comment by hexedpackets** [comment]
I believe you want https://github.com/flavioislima/HeroicGamesLauncher. This Heroic is a timeseries database that has no connection to that repo.
